// Human-entered Article 9 support fields. No inferred scientific species, HS code or production origin.
function updateMaterialInfo(id,input){const u=requireRole_(['ADMIN','MARKETING','EUDR_REVIEWER']);const m=rows_('02_SO_ITEM_MATERIAL').find(x=>x.id===id);if(!m)fail_('INVALID_INPUT','Material missing');order_(m.case_id,u);
 const allowed=['commodity','common_species','scientific_name','hs_cn_code','quantity','quantity_uom','production_countries','production_range','legality_evidence_ids','deforestation_evidence_ids','scope_status','scope_rule_version','metadata_source_document_id','metadata_reference'];Object.keys(input).forEach(k=>{if(!allowed.includes(k))fail_('INVALID_INPUT','Unknown metadata field');});
 if(!input.metadata_source_document_id||!text_(input.metadata_reference||'',500))fail_('INVALID_INPUT','Source document and page/field reference required');const metadataSource=document_(input.metadata_source_document_id,u);if(metadataSource.case_id!==m.case_id)fail_('INVALID_INPUT','Metadata source outside order');const value={};Object.keys(input).forEach(k=>{if(['production_countries','legality_evidence_ids','deforestation_evidence_ids'].includes(k)){if(!Array.isArray(input[k])||input[k].length>100)fail_('INVALID_INPUT','Expected a bounded array');if(k==='production_countries'){if(input[k].some(c=>typeof c!=='string'||! /^[A-Z]{2}$/.test(c)))fail_('INVALID_INPUT','Production countries must be ISO alpha-2 codes');}
 else input[k].forEach(id=>{const d=document_(id,u);if(d.case_id!==m.case_id)fail_('INVALID_INPUT','Evidence outside order');});value[k]=JSON.stringify([...new Set(input[k])]);}
 else value[k]=text_(String(input[k]),500);});
 if(value.quantity!==undefined&&value.quantity!==''&&(!Number.isFinite(Number(value.quantity))||Number(value.quantity)<0))fail_('INVALID_INPUT','Quantity must be nonnegative');
 if(value.scope_status){if(!['IN_SCOPE','OUT_OF_SCOPE','REVIEW_REQUIRED','NOT_PROVIDED'].includes(value.scope_status))fail_('INVALID_INPUT','Unknown scope status');if(['IN_SCOPE','OUT_OF_SCOPE'].includes(value.scope_status)){if(!['ADMIN','EUDR_REVIEWER'].includes(u.role)||!value.scope_rule_version||!value.hs_cn_code)fail_('PERMISSION_DENIED','Human reviewer, HS/CN code and checked version required');}}
 return lock_(()=>{patch_('02_SO_ITEM_MATERIAL',id,value);audit_('MATERIAL_METADATA_UPDATED',m.case_id,id,JSON.stringify(m),JSON.stringify(value),u.email);return true;});
}
function saveCertificate(id,input){const u=requireRole_(['ADMIN','EUDR_REVIEWER']),d=document_(id,u);if(!/FSC/i.test(d.document_type||''))fail_('INVALID_INPUT','FSC evidence required');const value={certificate_holder:text_(input.holder||'',200),certificate_no:text_(input.number||'',200),certificate_scope:text_(input.scope||'',500),issue_date:isoDate_(input.issue_date),expiry_date:isoDate_(input.expiry_date)};if(value.expiry_date<value.issue_date)fail_('INVALID_INPUT','Expiry is before issue');return lock_(()=>{patch_('06_DOCUMENT_REGISTER',id,value);const t=rows_('04_EVIDENCE_TRACKER').find(t=>t.id===d.task_id),tid=stable_('certificate-review:'+d.id);if(t&&!rows_('04_EVIDENCE_TRACKER').some(x=>x.id===tid))add_('04_EVIDENCE_TRACKER',{id:tid,case_id:d.case_id,material_id:d.material_id,evidence:'Certificate renewal review',evidence_block:'02_FSC_Certification',owner:t.assigned_reviewer||u.email,assigned_reviewer:t.assigned_reviewer||u.email,due:value.expiry_date,required:'NO',status:'REQUESTED',priority:'HIGH',created_at:now_(),updated_at:now_()});else if(t)patch_('04_EVIDENCE_TRACKER',tid,{due:value.expiry_date,status:'REQUESTED',updated_at:now_()});if(t)syncTaskCalendar_(rows_('04_EVIDENCE_TRACKER').find(x=>x.id===tid));notify_(t?t.owner:u.email,d.case_id,id,'Certificate expiry recorded: '+value.expiry_date);audit_('CERTIFICATE_METADATA_UPDATED',d.case_id,id,'',JSON.stringify(value),u.email);return true;});}
function saveCountryRisk(input){const u=requireRole_(['ADMIN']);const country=text_(input.country_code,2),risk=text_(input.risk_level,20),source=text_(input.source_url,1000),version=text_(input.rule_version,200);if(! /^[A-Z]{2}$/.test(country)||!['LOW','STANDARD','HIGH'].includes(risk)||!/^https:\/\/(eur-lex\.europa\.eu|environment\.ec\.europa\.eu|green-forum\.ec\.europa\.eu)\//.test(source)||!version)fail_('INVALID_INPUT','Official source, ISO country, risk and version required');const checked=isoDate_(input.checked_at),id=stable_(country+':'+version);return lock_(()=>{const value={id,country_code:country,risk_level:risk,rule_version:version,checked_at:checked,reviewed_by:u.email,source_url:source};if(rows_('22_COUNTRY_RISK').some(r=>r.id===id))patch_('22_COUNTRY_RISK',id,value);else add_('22_COUNTRY_RISK',value);audit_('COUNTRY_RISK_REVIEWED','',id,'',JSON.stringify(value),u.email);return true;});}
function materialIssues_(m){const issues=chainIssues_(m.id);if(!m.scientific_name||m.scientific_name==='NOT PROVIDED')issues.push('SCIENTIFIC_SPECIES_NOT_PROVIDED');if(!m.hs_cn_code||!m.scope_status||['REVIEW_REQUIRED','NOT_PROVIDED'].includes(m.scope_status))issues.push('PRODUCT_SCOPE_REVIEW_REQUIRED');if(!m.quantity||!m.quantity_uom)issues.push('MATERIAL_QUANTITY_NOT_PROVIDED');let countries=[];try{countries=JSON.parse(m.production_countries||'[]');}catch(e){}if(!countries.length)issues.push('PRODUCTION_COUNTRY_NOT_PROVIDED');
 if(!m.production_range)issues.push('PRODUCTION_RANGE_NOT_PROVIDED');if(m.scope_rule_version&&config_('ANNEX_I_VERSION')&&m.scope_rule_version!==config_('ANNEX_I_VERSION'))issues.push('SCOPE_VERSION_REVIEW_REQUIRED');countries.forEach(code=>{if(!rows_('22_COUNTRY_RISK').some(r=>r.country_code===code&&r.rule_version===config_('COUNTRY_RISK_VERSION')))issues.push('COUNTRY_RISK_REVIEW_REQUIRED:'+code);});
 for(const type of ['legality_evidence_ids','deforestation_evidence_ids']){let ids=[];try{ids=JSON.parse(m[type]||'[]');}catch(e){}if(!ids.length||ids.some(id=>!rows_('06_DOCUMENT_REGISTER').some(d=>d.id===id&&d.status==='APPROVED'&&d.active_version==='YES')))issues.push(type.toUpperCase()+'_MISSING');}
 return issues;
}
