import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createHash,createHmac,randomUUID} from 'node:crypto';
import {handler} from '../netlify/functions/call.mjs';
const root=new URL('../',import.meta.url),hash=s=>createHash('sha256').update(s).digest('hex');
function runtime(){
 const ctx={console,Date};vm.createContext(ctx);
 for(const file of ['Code.gs','Migration.gs','AuthService.gs','OrderService.gs','CalendarService.gs','DocumentService.gs','GeoService.gs','PromptService.gs','ExportService.gs','WorkspaceService.gs','MetadataService.gs','TransferService.gs','Bridge.gs'])vm.runInContext(fs.readFileSync(new URL('apps_script/'+file,root),'utf8'),ctx,{filename:file});
 const tables={};for(const name of Object.keys(vm.runInContext('SCHEMA',ctx)))tables[name]=[];
 const clone=o=>JSON.parse(JSON.stringify(o));
 ctx.rows_=n=>clone(tables[n]||[]);ctx.add_=(n,o)=>{const schema=vm.runInContext('SCHEMA',ctx)[n];tables[n].push(Object.fromEntries(schema.map(k=>[k,o[k]??''])));};
 ctx.patch_=(n,id,o)=>{const schema=vm.runInContext('SCHEMA',ctx)[n],record=tables[n].find(x=>x[schema[0]]===id);if(!record)throw Error('Record not found '+n+' '+id);Object.assign(record,clone(o));};ctx.lock_=f=>f();
 const properties={DB_ID:'staging-only',ROOT_ID:'root',CALENDAR_ID:'eudr-calendar',BRIDGE_SECRET:'b'.repeat(64),ALLOWED_ORIGINS:'https://koda-eudr-system.netlify.app'};
 ctx.PropertiesService={getScriptProperties:()=>({getProperty:k=>properties[k]||'',setProperties:p=>Object.assign(properties,p)})};
 ctx.Session={getActiveUser:()=>({getEmail:()=>''}),getEffectiveUser:()=>({getEmail:()=> 'admin@test.example'})};
 let fileNo=0;const files=new Map(),folders=new Map();
 function blob(bytes,type='text/plain',name='file'){return {getBytes:()=>[...bytes],getContentType:()=>type,getDataAsString:()=>Buffer.from(bytes).toString(),getName:()=>name,setName(n){name=n;return this;}};}
 function folder(id,name=id){const children=[],contained=[];const f={getId:()=>id,getName:()=>name,getFoldersByName:n=>iterator(children.filter(x=>x.getName()===n)),createFolder:n=>{const x=folder('folder-'+(++fileNo),n);children.push(x);return x;},getFilesByName:n=>iterator(contained.filter(x=>x.getName()===n)),createFile:b=>{const id='file-'+(++fileNo);let description='';const file={getId:()=>id,getName:()=>b.getName(),getBlob:()=>b,getSize:()=>b.getBytes().length,getDescription:()=>description,setDescription:d=>description=d};files.set(id,file);contained.push(file);return file;}};folders.set(id,f);return f;}
 function iterator(items){let i=0;return {hasNext:()=>i<items.length,next:()=>items[i++]};}folder('root');
 ctx.DriveApp={getFolderById:id=>{if(!folders.has(id))throw Error('Missing folder');return folders.get(id);},getFileById:id=>{if(!files.has(id))throw Error('Missing file');return files.get(id);}};
 ctx.Utilities={getUuid:randomUUID,DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>[...createHash('sha256').update(typeof s==='string'?s:Buffer.from(s)).digest()],computeHmacSha256Signature:(p,s)=>[...createHmac('sha256',s).update(p).digest()],base64Decode:s=>[...Buffer.from(s,'base64')],base64Encode:b=>Buffer.from(b).toString('base64'),newBlob:(bytes,type,name)=>blob(typeof bytes==='string'?[...Buffer.from(bytes)]:bytes,type,name),zip:bs=>blob([...Buffer.from(bs.map(b=>b.getName()+':'+b.getDataAsString()).join('\n'))],'application/zip','zip')};
 const seen=new Map();ctx.CacheService={getScriptCache:()=>({get:k=>seen.get(k),put:(k,v)=>seen.set(k,v)})};ctx.LockService={getScriptLock:()=>({waitLock(){},releaseLock(){}})};ctx.ContentService={MimeType:{JSON:'json'},createTextOutput:body=>({setMimeType:()=>({body})})};
 const events=new Map();let insertions=0;ctx.Calendar={Events:{get:(cal,id)=>{if(!events.has(id))throw Error('404 not found');return clone(events.get(id));},list:()=>({items:[]}),insert:(body,cal)=>{assert.equal(cal,'eudr-calendar');insertions++;events.set(body.id,clone(body));return body;},patch:(body,cal,id)=>{assert.equal(cal,'eudr-calendar');events.set(id,clone(body));return body;}}};
 const admin={email:'admin@test.example',name:'Admin',role:'ADMIN',active:'YES'},a={email:'a@supplier.example',role:'SUPPLIER_USER',active:'YES',supplier_id:'sa'},b={email:'b@supplier.example',role:'SUPPLIER_USER',active:'YES',supplier_id:'sb'};
 tables['05_OWNER_MASTER']=[admin,a,b,{email:'review@test.example',role:'EUDR_REVIEWER',active:'YES',assigned_orders:'["ca"]'}];tables['14_SUPPLIERS']=[{id:'sa',name:'Supplier A',active:'YES'},{id:'sb',name:'Supplier B',active:'YES'}];
 function actor(email=admin.email,action='uploadEvidence',key=randomUUID(),args=[]){ctx.BRIDGE_ACTOR=email;ctx.BRIDGE_REQUEST_KEY=key;ctx.BRIDGE_ACTION=action;ctx.BRIDGE_ARGS=args;}
 function seed(){tables['01_SO_MASTER']=[{id:'ca',so:'SO-A',owner:admin.email,folder:'root',status:'COLLECTING_EVIDENCE'},{id:'cb',so:'SO-B',owner:admin.email,folder:'root'}];tables['02_SO_ITEM_MATERIAL']=[{id:'ma',case_id:'ca',material:'Walnut',folder:'root'},{id:'mb',case_id:'cb',material:'MDF',folder:'root'}];tables['04_EVIDENCE_TRACKER']=[{id:'ta',case_id:'ca',material_id:'ma',supplier_id:'sa',owner:a.email,evidence:'INV',evidence_block:'01_Commercial_Shipping',required:'YES',status:'MISSING',due:'2026-10-09',assigned_reviewer:'review@test.example'},{id:'tb',case_id:'cb',material_id:'mb',supplier_id:'sb',owner:b.email,status:'MISSING'}];}
 actor();return {ctx,tables,actor,seed,files,folders,properties,events,get insertions(){return insertions;}};
}
const pdf={expected_document_id:'',name:'invoice.pdf',type:'application/pdf',data:Buffer.from('%PDF-1.7\nSynthetic test fixture only').toString('base64')};
const code=e=>x=>x.code===e;

test('closure requires human confirmation, complete traceability, fresh legal review and export',()=>{
 const r=runtime();r.seed();assert.throws(()=>r.ctx.completeCase('ca',{confirmed:false,comment:'TEST'}),code('HUMAN_CONFIRMATION_REQUIRED'));
 assert.throws(()=>r.ctx.completeCase('ca',{confirmed:true,comment:'TEST'}),code('EVIDENCE_INCOMPLETE'));
 r.tables['04_EVIDENCE_TRACKER'][0].status='APPROVED';r.tables['09_CONFIG']=[{key:'RULES_CONFIRMED',value:'YES'}];r.ctx.materialIssues_=()=>[];
 assert.throws(()=>r.ctx.completeCase('ca',{confirmed:true,comment:'TEST'}),code('LEGAL_REVIEW_DUE'));r.ctx.legalState_=()=>({reviewDue:false});
 assert.throws(()=>r.ctx.completeCase('ca',{confirmed:true,comment:'TEST'}),code('EXPORT_REQUIRED'));r.tables['19_EXPORT_LOG']=[{id:'e',case_id:'ca',include_history:'NO'}];
 r.tables['06_DOCUMENT_REGISTER']=[{id:'c',case_id:'ca',active_version:'YES',expiry_date:'2000-01-01'}];assert.throws(()=>r.ctx.completeCase('ca',{confirmed:true,comment:'TEST'}),code('EVIDENCE_INCOMPLETE'));
 r.tables['06_DOCUMENT_REGISTER']=[];r.ctx.completeCase('ca',{confirmed:true,comment:'TEST internal closure'});assert.equal(r.tables['01_SO_MASTER'][0].status,'CLOSED');const log=r.tables['08_ACTIVITY_LOG'].at(-1);assert.equal(log.role,'ADMIN');assert.equal(log.order_no,'SO-A');assert.equal(log.comment,'TEST internal closure');
 r.actor('a@supplier.example');assert.throws(()=>r.ctx.completeCase('ca',{confirmed:true,comment:'TEST'}),code('PERMISSION_DENIED'));
});
test('invalid coordinate precision configuration cannot bypass validation',()=>{const r=runtime();for(const value of ['NaN','6.5','5','13'])assert.throws(()=>r.ctx.saveSettings({GEO_MIN_DECIMALS:value}),code('INVALID_INPUT'));});

test('Apps Script files parse and additive schema reuses existing tables',()=>{const r=runtime(),schema=vm.runInContext('SCHEMA',r.ctx);assert.equal(schema['05_OWNER_MASTER'][0],'email');assert.equal(schema['01_SO_MASTER'][1],'so');assert.ok(schema['06_DOCUMENT_REGISTER'].includes('active_version'));assert.equal(new Set(schema['06_DOCUMENT_REGISTER']).size,schema['06_DOCUMENT_REGISTER'].length);});
test('disabled user and disabled supplier are denied immediately',()=>{const r=runtime();r.tables['05_OWNER_MASTER'][0].active='NO';assert.throws(()=>r.ctx.user_(),code('AUTH_REQUIRED'));r.actor('a@supplier.example');r.tables['14_SUPPLIERS'][0].active='NO';assert.throws(()=>r.ctx.user_(),code('PERMISSION_DENIED'));});
test('supplier bootstrap and direct document access cannot cross supplier/order scope',()=>{const r=runtime();r.seed();r.tables['06_DOCUMENT_REGISTER']=[{id:'db',case_id:'cb',task_id:'tb',supplier_id:'sb',kind:'EVIDENCE'}];r.actor('a@supplier.example');const x=r.ctx.bootstrap();assert.deepEqual(x.cases.map(c=>c.id),['ca']);assert.deepEqual(x.materials.map(m=>m.id),['ma']);assert.equal(x.cases[0].folder,'');assert.equal(x.docs.length,0);assert.equal(x.owners.length,0);assert.equal(x.audit.length,0);assert.throws(()=>r.ctx.getDocument('db'),code('PERMISSION_DENIED'));assert.throws(()=>r.ctx.uploadEvidence('tb',pdf),code('PERMISSION_DENIED'));});
test('supplier chain and plot metadata stay within assigned material even on the same order',()=>{const r=runtime();r.seed();r.tables['02_SO_ITEM_MATERIAL'].push({id:'other',case_id:'ca',material:'Veneer',folder:'root'});r.tables['15_SUPPLY_CHAIN']=[{id:'visible',case_id:'ca',material_id:'ma',supplier_id:'sa'},{id:'hidden',case_id:'ca',material_id:'other',supplier_id:'sa'}];r.tables['17_GEO_LOCATIONS']=[{id:'visible-plot',case_id:'ca',material_id:'ma',supplier_id:'sa'},{id:'hidden-plot',case_id:'ca',material_id:'other',supplier_id:'sa'}];r.actor('a@supplier.example');const x=r.ctx.bootstrap();assert.deepEqual(x.materials.map(m=>m.id),['ma']);assert.deepEqual(x.chain.map(n=>n.id),['visible']);assert.deepEqual(x.geo.map(g=>g.id),['visible-plot']);});
test('supplier cannot manage user, create SO, review, export or use prompt studio',()=>{const r=runtime();r.seed();r.actor('a@supplier.example');for(const fn of [()=>r.ctx.manageUser({}),()=>r.ctx.createOrder({}),()=>r.ctx.reviewDocument('x','APPROVED',''),()=>r.ctx.exportPackage('ca',{}),()=>r.ctx.getAiPrompt('ca','MATERIAL_EXTRACTION','')])assert.throws(fn,code('PERMISSION_DENIED'));});
test('personal assignment owner can see own order evidence without global scope',()=>{const r=runtime();r.seed();r.tables['05_OWNER_MASTER'].push({email:'mark@test.example',role:'MARKETING',active:'YES'});r.tables['01_SO_MASTER'][0].owner='mark@test.example';r.actor('mark@test.example');const x=r.ctx.bootstrap();assert.deepEqual(x.cases.map(c=>c.id),['ca']);assert.deepEqual(x.tasks.map(t=>t.id),['ta']);});
test('invalid MIME signature and invalid date do not create Drive folders',()=>{const r=runtime();const before=r.folders.size;assert.throws(()=>r.ctx.createOrder({so:'SO-BAD',file:{...pdf,data:Buffer.from('<html>x</html>').toString('base64')}}),code('INVALID_FILE'));assert.equal(r.folders.size,before);assert.throws(()=>r.ctx.isoDate_('2026-02-30'),code('INVALID_INPUT'));assert.throws(()=>r.ctx.validateFile_({...pdf,type:'text/html'}),code('INVALID_FILE'));});
test('order retry reuses folder, file and order; duplicate SO is held',()=>{const r=runtime(),input={so:'SO25-2183',customer:'TEST CUSTOMER',due:'2026-10-09',file:pdf},key=randomUUID();r.actor(undefined,'createOrder',key,[input]);const a=r.ctx.createOrder(input),count=r.folders.size;r.actor(undefined,'createOrder',key,[input]);assert.deepEqual(r.ctx.createOrder(input),a);assert.equal(r.folders.size,count);assert.equal(r.tables['01_SO_MASTER'].length,1);assert.equal(r.tables['06_DOCUMENT_REGISTER'].length,1);r.actor(undefined,'createOrder',randomUUID(),[input]);assert.throws(()=>r.ctx.createOrder(input),code('DUPLICATE_ORDER'));});
test('idempotency key cannot be reused with changed args',()=>{const r=runtime(),key=randomUUID();r.actor(undefined,'action',key,['one']);r.ctx.withOperation_(()=>({done:true}));r.actor(undefined,'action',key,['two']);assert.throws(()=>r.ctx.withOperation_(()=>({done:true})),code('VERSION_CONFLICT'));});
test('material preview validates exact order, duplicates, citation and category',()=>{const r=runtime();r.seed();const result={order_no:'SO-A',product:'TEST',materials:[{material_name_original:'FSC SOLID WALNUT',material_name_normalized:'Walnut',material_category:'SOLID_WOOD',scientific_name:null,source_reference:'SO page 1'}]};const p=r.ctx.previewMaterials('ca',JSON.stringify(result));assert.equal(p.materials[0].scientific_name,'NOT PROVIDED');assert.equal(r.tables['02_SO_ITEM_MATERIAL'].length,2);assert.throws(()=>r.ctx.previewMaterials('ca','broken'),code('INVALID_JSON'));assert.throws(()=>r.ctx.previewMaterials('ca',JSON.stringify({...result,order_no:'SO-B'})),code('INVALID_INPUT'));assert.throws(()=>r.ctx.previewMaterials('ca',JSON.stringify({...result,materials:[...result.materials,...result.materials]})),code('DUPLICATE_MATERIAL'));assert.throws(()=>r.ctx.confirmMaterials('ca',JSON.stringify(result),{confirmed:false}),code('VERSION_CONFLICT'));});
test('material confirmation creates required evidence once and supports retry',()=>{const r=runtime();r.seed();r.tables['03_EVIDENCE_REQUIREMENT']=[{id:'R1',material:'*',evidence:'INV',tier:'DIRECT',enabled:'YES'}];const obj={order_no:'SO-A',product:'TEST',materials:[{material_name_original:'Walnut',material_name_normalized:'Walnut',material_category:'SOLID_WOOD',scientific_name:null,source_reference:'SO page 1'}]},json=JSON.stringify(obj),p=r.ctx.previewMaterials('ca',json),key=randomUUID(),confirmation={confirmed:true,preview_hash:p.preview_hash};r.actor(undefined,'confirmMaterials',key,['ca',json,confirmation]);r.ctx.confirmMaterials('ca',json,confirmation);const count=r.tables['04_EVIDENCE_TRACKER'].length;r.ctx.confirmMaterials('ca',json,confirmation);assert.equal(r.tables['04_EVIDENCE_TRACKER'].length,count);});
test('document rejection history survives replacement and only one version stays active',()=>{const r=runtime();r.seed();r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);const first=r.ctx.uploadEvidence('ta',pdf);r.ctx.submitDocument(first.id);r.actor('review@test.example');assert.throws(()=>r.ctx.reviewDocument(first.id,'REJECTED',''),code('INVALID_INPUT'));r.ctx.reviewDocument(first.id,'REJECTED','Supplier mismatch');r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);const second=r.ctx.uploadEvidence('ta',{...pdf,expected_document_id:first.id});const docs=r.tables['06_DOCUMENT_REGISTER'];assert.equal(docs.find(d=>d.id===first.id).status,'REJECTED');assert.equal(docs.find(d=>d.id===first.id).active_version,'NO');assert.equal(docs.filter(d=>d.active_version==='YES').length,1);assert.equal(second.version,2);assert.ok(r.tables['08_ACTIVITY_LOG'].some(a=>a.action==='DOCUMENT_REJECTED'));});
test('internal comments stay internal for supplier document viewer',()=>{const r=runtime();r.seed();r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);const d=r.ctx.uploadEvidence('ta',pdf);r.actor();r.ctx.addComment(d.id,{visibility:'INTERNAL_ONLY',comment:'INTERNAL TEST NOTE'});r.actor('a@supplier.example');assert.equal(r.ctx.getDocument(d.id).comments.length,0);assert.throws(()=>r.ctx.addComment(d.id,{visibility:'INTERNAL_ONLY',comment:'x'}),code('PERMISSION_DENIED'));});
test('reviewer acceptance requires submission; supplier cannot bypass with updateTask',()=>{const r=runtime();r.seed();r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);const d=r.ctx.uploadEvidence('ta',pdf);r.actor('review@test.example');assert.throws(()=>r.ctx.reviewDocument(d.id,'APPROVED',''),code('VERSION_CONFLICT'));r.ctx.submitDocument(d.id);r.ctx.reviewDocument(d.id,'APPROVED','Evidence checked');assert.equal(r.tables['04_EVIDENCE_TRACKER'][0].status,'APPROVED');r.actor('a@supplier.example');assert.throws(()=>r.ctx.updateTask('ta',{status:'APPROVED'}),code('PERMISSION_DENIED'));});
test('calendar retry, reschedule, owner change and completion keep one event and history',()=>{const r=runtime();r.seed();const t=r.tables['04_EVIDENCE_TRACKER'][0];r.ctx.syncTaskCalendar_(t);r.ctx.syncTaskCalendar_(t);assert.equal(r.insertions,1);const id=t.calendar_event_id;r.ctx.syncTaskCalendar_({...t,due:'2026-10-12',owner:'review@test.example',status:'APPROVED'});assert.equal(r.insertions,1);assert.equal(r.events.get(id).start.date,'2026-10-12');assert.match(r.events.get(id).summary,/\[DONE\]/);assert.match(r.events.get(id).description,/review@test.example/);assert.equal(t.calendar_event_id,id);});
test('calendar permission failure saves task and never uses primary calendar',()=>{const r=runtime();r.seed();r.ctx.Calendar.Events.get=()=>{throw Error('403 Forbidden');};const x=r.ctx.updateTask('ta',{due:'2026-10-13'});assert.equal(x.saved,true);assert.equal(x.calendar.status,'CALENDAR_ACCESS_REQUIRED');assert.equal(r.tables['04_EVIDENCE_TRACKER'][0].due,'2026-10-13');assert.equal(r.insertions,0);});
test('GEO: valid point/polygon, out of range, malformed, closure, duplicate and intersection',()=>{const r=runtime(),v=g=>r.ctx.validateGeometry_(g);assert.equal(v({type:'Point',coordinates:[106.123456,10.123456]}).type,'Point');assert.equal(v({type:'Polygon',coordinates:[[[1,1],[2,1],[2,2],[1,2],[1,1]]]}).type,'Polygon');for(const g of [{type:'Point',coordinates:[181,0]},{type:'Point',coordinates:['106',10]},{type:'Polygon',coordinates:[[[1,1],[2,1],[2,2],[1,2]]]},{type:'Polygon',coordinates:[[[0,0],[2,2],[0,2],[2,0],[0,0]]]},{type:'Polygon',coordinates:[[[1,1],[2,1],[2,2],[2,1],[1,1]]]},{type:'MultiPolygon',coordinates:[]}])assert.throws(()=>v(g),code('INVALID_GEO'));});
test('plot >4 ha requires polygon; production country/source chain are required',()=>{const r=runtime();r.seed();r.tables['15_SUPPLY_CHAIN']=[{id:'node',case_id:'ca',material_id:'ma',supplier_id:'sa',node_type:'PLOT',plot_id:'plot-a'}];r.tables['06_DOCUMENT_REGISTER']=[{id:'d',case_id:'ca',material_id:'ma',status:'APPROVED',active_version:'YES'}];const input={material_id:'ma',chain_node_id:'node',plot_id:'plot-a',country_of_production:'US',production_range:'2026-01-01 / 2026-02-01',area_ha:5,coordinate_precision_digits:6,source_document_id:'d',geometry:{type:'Point',coordinates:[106.123456,10.123456]}};assert.throws(()=>r.ctx.saveGeo('ca',input),code('INVALID_GEO'));assert.throws(()=>r.ctx.saveGeo('ca',{...input,area_ha:2,country_of_production:''}),code('INVALID_GEO'));r.actor(undefined,'saveGeo',randomUUID(),['ca',input]);const x=r.ctx.saveGeo('ca',{...input,area_ha:2});assert.equal(x.status,'REVIEW_REQUIRED');assert.throws(()=>r.ctx.reviewGeo(x.id,{status:'VERIFIED',notes:'TEST NOTE'}),code('LEGAL_REVIEW_DUE'));});
test('deep upstream chain is not capped at two tiers and broken chain is flagged',()=>{const r=runtime();r.seed();r.tables['15_SUPPLY_CHAIN']=[0,1,2,3,4].map(i=>({id:'n'+i,material_id:'ma',parent_id:i?'n'+(i-1):'',node_type:i===4?'PLOT':'PROCESSOR',source_document_id:'source'}));r.tables['06_DOCUMENT_REGISTER']=[{id:'source',status:'APPROVED',active_version:'YES'}];r.tables['17_GEO_LOCATIONS']=[{material_id:'ma',chain_node_id:'n4',verification_status:'VERIFIED',source_document_id:'source'}];assert.equal(r.ctx.chainIssues_('ma').length,0);r.tables['15_SUPPLY_CHAIN'][3].parent_id='missing';assert.ok(r.ctx.chainIssues_('ma').some(i=>i.startsWith('BROKEN_PARENT')));});
test('FSC approved without GEO/upstream cannot become operator-ready',()=>{const r=runtime();r.seed();r.tables['04_EVIDENCE_TRACKER'][0].status='APPROVED';const c=r.ctx.bootstrap().cases.find(c=>c.id==='ca');assert.notEqual(c.status,'READY_FOR_OPERATOR_REVIEW');assert.ok(c.issues.length);});
test('redaction/subtitle prompts require human-approved active source; no API calls',()=>{const r=runtime();r.seed();r.tables['06_DOCUMENT_REGISTER']=[{id:'d',case_id:'ca',name:'test.pdf',kind:'EVIDENCE',status:'UPLOADED',active_version:'YES'}];assert.throws(()=>r.ctx.getAiPrompt('ca','PRICE_REDACTION','d'),code('VERSION_CONFLICT'));Object.assign(r.tables['06_DOCUMENT_REGISTER'][0],{status:'APPROVED'});const x=r.ctx.getAiPrompt('ca','PRICE_REDACTION','d');assert.match(x.prompt,/underlying text/);assert.match(x.prompt,/Human Redaction Verified/);assert.ok(r.tables['18_AI_PROMPT_RUNS'].length);const frontendCode=fs.readFileSync(new URL('public/app.js',root),'utf8');assert.doesNotMatch(frontendCode,/api\.openai\.com|chatgpt\.com\/\?q=/);});
test('processed copies cannot become source evidence or replace original task review',()=>{const r=runtime();r.seed();r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);const original=r.ctx.uploadEvidence('ta',pdf);r.ctx.submitDocument(original.id);r.actor('review@test.example');r.ctx.reviewDocument(original.id,'APPROVED','TEST');r.actor('review@test.example','uploadProcessed',randomUUID(),[original.id,'REDACTED',pdf]);const processed=r.ctx.uploadProcessed(original.id,'REDACTED',pdf);assert.throws(()=>r.ctx.reviewDocument(processed.id,'APPROVED',''),code('INVALID_INPUT'));assert.equal(r.tables['04_EVIDENCE_TRACKER'][0].status,'APPROVED');r.ctx.verifyProcessed(processed.id,{verified:true,notes:'TEST PDF verified'});assert.throws(()=>r.ctx.getAiPrompt('ca','PRICE_REDACTION',processed.id),code('VERSION_CONFLICT'));assert.throws(()=>r.ctx.uploadProcessed(processed.id,'EN_SUBTITLE',pdf),code('VERSION_CONFLICT'));assert.throws(()=>r.ctx.beginUpload('ta',{name:'x.pdf',type:'application/pdf',size:20,sha256:'a'.repeat(64),kind:'REDACTED',source_document_id:processed.id,expected_document_id:original.id}),code('INVALID_INPUT'));r.tables['06_DOCUMENT_REGISTER'].push({id:'other-processed',case_id:'ca',task_id:'ta',kind:'REDACTED',source_document_id:'another-original',supplier_id:'sa',version:1});assert.deepEqual(r.ctx.getDocument(processed.id).versions.map(v=>v.id),[processed.id]);});
test('export rejects rejected/inactive docs and unverified processed output',()=>{const r=runtime();r.seed();r.tables['06_DOCUMENT_REGISTER']=[{id:'d',case_id:'ca',kind:'EVIDENCE',status:'REJECTED',active_version:'YES'}];assert.throws(()=>r.ctx.exportPackage('ca',{document_ids:['d']}),code('VERSION_CONFLICT'));Object.assign(r.tables['06_DOCUMENT_REGISTER'][0],{kind:'REDACTED',status:'APPROVED',redaction_verified:'NO'});r.actor(undefined,'exportPackage',randomUUID(),[]);assert.throws(()=>r.ctx.exportPackage('ca',{}),code('VERIFICATION_REQUIRED'));});
test('selected export produces manifest once and export download obeys scope',()=>{const r=runtime();r.seed();r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);const d=r.ctx.uploadEvidence('ta',pdf);r.ctx.submitDocument(d.id);r.actor('review@test.example');r.ctx.reviewDocument(d.id,'APPROVED','TEST');const key=randomUUID();r.actor('review@test.example','exportPackage',key,['ca',{}]);const ex=r.ctx.exportPackage('ca',{});const count=r.files.size;r.ctx.exportPackage('ca',{});assert.equal(r.files.size,count);assert.equal(r.tables['19_EXPORT_LOG'].length,1);const f=r.ctx.getDocument(ex.download_id);assert.equal(f.type,'application/zip');assert.match(Buffer.from(f.data,'base64').toString(),/Export_Manifest/);r.actor('a@supplier.example');assert.throws(()=>r.ctx.getDocument(ex.download_id),code('PERMISSION_DENIED'));});
test('CSV/Sheet injection is neutralized and audit has no public edit endpoint',()=>{const r=runtime();assert.equal(r.ctx.safe_('=IMPORTXML("x")'),"'=IMPORTXML(\"x\")");assert.match(r.ctx.csv_([['=1+1']]),/"'=1\+1"/);assert.equal(Object.hasOwn(r.ctx.BRIDGE_ACTIONS,'patch_'),false);assert.equal(Object.hasOwn(r.ctx.BRIDGE_ACTIONS,'setup'),false);});
test('signed request verifies origin, HMAC, replay and active actor',()=>{const r=runtime(),secret=r.properties.BRIDGE_SECRET;const envelope=(changes={})=>{const payload=JSON.stringify({ts:Date.now(),nonce:randomUUID(),actor:'admin@test.example',action:'bootstrap',args:[],requestKey:randomUUID(),origin:'https://koda-eudr-system.netlify.app',...changes});return {payload,signature:createHmac('sha256',secret).update(payload).digest('hex')};},post=x=>JSON.parse(r.ctx.doPost({postData:{contents:JSON.stringify(x)}}).body),e=envelope();assert.equal(post(e).ok,true);assert.equal(post(e).error.code,'AUTH_REQUIRED');assert.equal(post({...envelope(),signature:'bad'}).error.code,'AUTH_REQUIRED');assert.equal(post(envelope({origin:'https://evil.example'})).error.code,'PERMISSION_DENIED');assert.equal(post(envelope({ts:Date.now()-600000})).error.code,'AUTH_REQUIRED');assert.equal(post(envelope({action:'setup'})).error.code,'UNKNOWN_ACTION');r.tables['05_OWNER_MASTER'][0].active='NO';assert.equal(post(envelope()).error.code,'AUTH_REQUIRED');});
test('Netlify authenticates separate principals, rejects spoofing, expiry and origins',async()=>{const token='a'.repeat(64),secret='b'.repeat(64),origin='https://koda-eudr-system.netlify.app';Object.assign(process.env,{BRIDGE_SECRET:secret,APPS_SCRIPT_WEBAPP_URL:'https://script.google.com/macros/s/testdeployment/exec',ALLOWED_ORIGINS:origin,TOKEN_HASHES_JSON:JSON.stringify([{sha256:hash(token),email:'a@supplier.example',expires_at:'2099-01-01T00:00:00Z'}]),ALLOW_PILOT_ADMIN:'false'});const original=globalThis.fetch;let signed;globalThis.fetch=async(url,opt)=>{signed=JSON.parse(opt.body);return {ok:true,text:async()=>JSON.stringify({ok:true,data:{ready:true}})};};try{const req=(changes={})=>({httpMethod:'POST',headers:{origin,authorization:'Bearer '+token},body:JSON.stringify({action:'bootstrap',args:[],actor:'admin@test.example'}),...changes});assert.equal((await handler(req())).statusCode,200);assert.equal(JSON.parse(signed.payload).actor,'a@supplier.example');assert.equal(signed.signature,createHmac('sha256',secret).update(signed.payload).digest('hex'));assert.equal((await handler(req({headers:{origin:'https://evil.example',authorization:'Bearer '+token}}))).statusCode,403);assert.equal((await handler(req({headers:{origin,authorization:'Bearer wrong'}}))).statusCode,401);process.env.TOKEN_HASHES_JSON=JSON.stringify([{sha256:hash(token),email:'a@supplier.example',expires_at:'2000-01-01'}]);assert.equal((await handler(req())).statusCode,401);}finally{globalThis.fetch=original;}});
test('material metadata needs cited source; supplier cannot edit species or legal scope',()=>{const r=runtime();r.seed();r.tables['06_DOCUMENT_REGISTER']=[{id:'source',case_id:'ca',material_id:'ma',status:'APPROVED',active_version:'YES'}];const input={metadata_source_document_id:'source',metadata_reference:'TEST page 1',common_species:'Walnut',scientific_name:'NOT PROVIDED',production_countries:['US'],quantity:'250',quantity_uom:'Each',hs_cn_code:'TEST_ONLY',scope_status:'IN_SCOPE',scope_rule_version:'TEST_ONLY',legality_evidence_ids:['source'],deforestation_evidence_ids:['source']};r.ctx.updateMaterialInfo('ma',input);assert.equal(r.tables['02_SO_ITEM_MATERIAL'][0].production_countries,'["US"]');assert.equal(r.tables['02_SO_ITEM_MATERIAL'][0].scientific_name,'NOT PROVIDED');assert.throws(()=>r.ctx.updateMaterialInfo('ma',{...input,metadata_reference:''}),code('INVALID_INPUT'));r.actor('a@supplier.example');assert.throws(()=>r.ctx.updateMaterialInfo('ma',input),code('PERMISSION_DENIED'));});
test('scientific-name, scope, legality and production-country gaps block operator-ready',()=>{const r=runtime();r.seed();const issues=r.ctx.materialIssues_(r.tables['02_SO_ITEM_MATERIAL'][0]);assert.ok(issues.includes('SCIENTIFIC_SPECIES_NOT_PROVIDED'));assert.ok(issues.includes('PRODUCTION_COUNTRY_NOT_PROVIDED'));assert.ok(issues.includes('PRODUCT_SCOPE_REVIEW_REQUIRED'));assert.ok(issues.includes('LEGALITY_EVIDENCE_IDS_MISSING'));assert.ok(issues.includes('DEFORESTATION_EVIDENCE_IDS_MISSING'));});
test('country classification records require EU sources and are versioned by production country',()=>{const r=runtime();assert.throws(()=>r.ctx.saveCountryRisk({country_code:'US',risk_level:'LOW',source_url:'https://example.com',rule_version:'TEST',checked_at:'2026-10-06'}),code('INVALID_INPUT'));r.ctx.saveCountryRisk({country_code:'US',risk_level:'LOW',source_url:'https://eur-lex.europa.eu/TEST',rule_version:'TEST',checked_at:'2026-10-06'});assert.equal(r.tables['22_COUNTRY_RISK'].length,1);assert.equal(r.tables['22_COUNTRY_RISK'][0].reviewed_by,'admin@test.example');});
test('legal freshness rejects malformed review dates and missing reviewer',()=>{const r=runtime();r.tables['09_CONFIG']=[{key:'LAST_LEGAL_REVIEW_DATE',value:'broken'},{key:'LEGAL_RULE_VERSION',value:'TEST'},{key:'ANNEX_I_VERSION',value:'TEST'},{key:'COUNTRY_RISK_VERSION',value:'TEST'}];assert.equal(r.ctx.legalState_().reviewDue,true);assert.throws(()=>r.ctx.saveSettings({LAST_LEGAL_REVIEW_DATE:'broken'}),code('INVALID_INPUT'));assert.throws(()=>r.ctx.saveSettings({LEGAL_REVIEW_MAX_DAYS:'0'}),code('INVALID_INPUT'));});
test('certificate expiry records create one renewal task without counting it as required evidence',()=>{const r=runtime();r.seed();r.tables['06_DOCUMENT_REGISTER']=[{id:'cert',case_id:'ca',task_id:'ta',material_id:'ma',document_type:'FSC Cert'}];const input={holder:'TEST',number:'TEST-CERT',scope:'TEST SCOPE',issue_date:'2026-01-01',expiry_date:'2026-10-01'};r.ctx.saveCertificate('cert',input);r.ctx.saveCertificate('cert',input);assert.equal(r.tables['04_EVIDENCE_TRACKER'].filter(t=>t.evidence==='Certificate renewal review').length,1);assert.equal(r.tables['04_EVIDENCE_TRACKER'].find(t=>t.evidence==='Certificate renewal review').required,'NO');assert.throws(()=>r.ctx.saveCertificate('cert',{...input,expiry_date:'2025-01-01'}),code('INVALID_INPUT'));});
test('migration validates all headers before writing and never touches auxiliary tabs',()=>{const r=runtime(),legacy=JSON.parse(fs.readFileSync(new URL('tests/fixtures/baseline-schema.json',root),'utf8')),sheets=new Map();let writes=0;
 function sheet(name,headers){let h=[...headers],max=Math.max(26,h.length);const s={getDataRange:()=>({getValues:()=>[h, name==='05_OWNER_MASTER'?['admin@test.example','','','ADMIN','YES']:[]]}),getLastColumn:()=>h.length,getMaxColumns:()=>max,insertColumnsAfter:(start,count)=>max+=count,setFrozenRows(){},getRange:(row,col,rows,cols)=>({getValues:()=>[h.slice(col-1,col-1+cols)],setValues:v=>{writes++;v[0].forEach((x,i)=>h[col-1+i]=x);}})};sheets.set(name,s);return s;}
 for(const [n,h]of Object.entries(legacy))sheet(n,h);const untouched=sheet('12_AI_ASSISTANT',['KEEP','EXACT']);sheet('13_PILOT_REVIEW',['KEEP TOO']);const db={getSheetByName:n=>sheets.get(n),insertSheet:n=>sheet(n,[])};r.ctx.SpreadsheetApp={openById:()=>db};
 // Invalid header must fail before the first extension.
 const original=sheets.get('09_CONFIG');sheet('09_CONFIG',['WRONG','value']);assert.throws(()=>r.ctx.migrateV2(),/SCHEMA_MISMATCH/);assert.equal(writes,0);sheets.set('09_CONFIG',original);const x=r.ctx.migrateV2();assert.equal(x.version,'2.0.0-staging');assert.equal(sheets.get('12_AI_ASSISTANT'),untouched);assert.ok(sheets.has('22_COUNTRY_RISK'));const count=writes;r.ctx.migrateV2();assert.equal(writes,count);
});
test('optimistic version check stops stale evidence upload',()=>{const r=runtime();r.seed();r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);r.ctx.uploadEvidence('ta',pdf);r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);assert.throws(()=>r.ctx.uploadEvidence('ta',pdf),code('VERSION_CONFLICT'));assert.equal(r.tables['06_DOCUMENT_REGISTER'].length,1);});
test('chunked upload assembles >3 MiB, verifies checksum and keeps one active document on retry',()=>{const r=runtime();r.seed();const bytes=Buffer.concat([Buffer.from('%PDF-1.7\nTEST ONLY\n'),Buffer.alloc(3*1024*1024+128,65)]),meta={name:'large-test.pdf',type:'application/pdf',size:bytes.length,sha256:hash(bytes),expected_document_id:''};r.actor('a@supplier.example','beginUpload',randomUUID(),['ta',meta]);const session=r.ctx.beginUpload('ta',meta);assert.equal(session.chunk_count,4);
 for(let i=0;i<session.chunk_count;i++){const data=bytes.subarray(i*1048576,(i+1)*1048576).toString('base64');r.ctx.uploadChunk(session.id,i,data);r.ctx.uploadChunk(session.id,i,data);}
 r.actor('a@supplier.example','finishUpload',randomUUID(),[session.id]);const result=r.ctx.finishUpload(session.id);assert.equal(r.tables['06_DOCUMENT_REGISTER'].length,1);assert.equal(r.files.get(r.tables['06_DOCUMENT_REGISTER'][0].file_id).getSize(),bytes.length);const count=r.files.size;assert.equal(r.ctx.finishUpload(session.id).id,result.id);assert.equal(r.files.size,count);const doc=r.ctx.getDocument(result.id);assert.equal(doc.download_chunked,true);assert.equal(doc.data,null);assert.equal(doc.size,bytes.length);
});
test('chunk upload rejects missing, altered, wrong-size and cross-user chunks',()=>{const r=runtime();r.seed();const bytes=Buffer.from('%PDF-1.7\nTEST'),metadata={name:'x.pdf',type:'application/pdf',size:bytes.length,sha256:hash(bytes),expected_document_id:''};r.actor('a@supplier.example','beginUpload',randomUUID(),['ta',metadata]);const session=r.ctx.beginUpload('ta',metadata);assert.throws(()=>r.ctx.finishUpload(session.id),code('INCOMPLETE_UPLOAD'));assert.throws(()=>r.ctx.uploadChunk(session.id,0,'YQ=='),code('INVALID_FILE'));r.ctx.uploadChunk(session.id,0,bytes.toString('base64'));assert.throws(()=>r.ctx.uploadChunk(session.id,0,Buffer.alloc(bytes.length,1).toString('base64')),code('VERSION_CONFLICT'));r.actor('b@supplier.example');assert.throws(()=>r.ctx.uploadChunk(session.id,0,bytes.toString('base64')),code('PERMISSION_DENIED'));});
test('bounded chunk download rechecks permission and refuses whole-file or short responses',()=>{const r=runtime();r.seed();r.actor('a@supplier.example','uploadEvidence',randomUUID(),['ta',pdf]);const result=r.ctx.uploadEvidence('ta',pdf),record=r.tables['06_DOCUMENT_REGISTER'][0],bytes=r.files.get(record.file_id).getBlob().getBytes();let sent;r.ctx.ScriptApp={getOAuthToken:()=> 'TEST_SERVER_TOKEN'};r.ctx.UrlFetchApp={fetch:(url,opt)=>{sent={url,opt};return {getResponseCode:()=>206,getBlob:()=>r.ctx.Utilities.newBlob(bytes)}}};const chunk=r.ctx.getDocumentChunk(result.id,0);assert.equal(chunk.size,bytes.length);assert.equal(sent.opt.headers.Range,'bytes=0-'+(bytes.length-1));assert.match(sent.url,/googleapis\.com\/drive\/v3\/files/);r.ctx.UrlFetchApp.fetch=()=>({getResponseCode:()=>200});assert.throws(()=>r.ctx.getDocumentChunk(result.id,0),code('DOWNLOAD_FAILED'));r.actor('b@supplier.example');assert.throws(()=>r.ctx.getDocumentChunk(result.id,0),code('PERMISSION_DENIED'));});
test('all HTTP actions resolve to backend handlers and frontend action calls are supported',()=>{const r=runtime(),netlify=fs.readFileSync(new URL('netlify/functions/call.mjs',root),'utf8'),frontend=fs.readFileSync(new URL('public/app.js',root),'utf8'),allowed=new Set([...netlify.match(/const actions=new Set\(\[([^\]]+)\]/)[1].matchAll(/'([^']+)'/g)].map(m=>m[1]));for(const action of Object.keys(r.ctx.BRIDGE_ACTIONS))assert.ok(allowed.has(action),action);for(const action of allowed)assert.equal(typeof r.ctx.BRIDGE_ACTIONS[action],'function',action);for(const m of frontend.matchAll(/(?:call|act)\('([^']+)'/g))assert.ok(allowed.has(m[1]),m[1]);});
