import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createHmac, randomUUID} from 'node:crypto';
import {handler} from '../netlify/functions/call.mjs';

const secret = 'b'.repeat(64), token = 't'.repeat(64), actor = 'admin@example.test';
Object.assign(process.env,{BRIDGE_SECRET:secret,PILOT_ADMIN_TOKEN:token,PILOT_ADMIN_EMAIL:actor,APPS_SCRIPT_WEBAPP_URL:'https://script.google.com/macros/s/abc123/exec'});
const context = {console};vm.createContext(context);
vm.runInContext(fs.readFileSync(new URL('../apps_script/Code.gs',import.meta.url),'utf8'),context);
vm.runInContext(fs.readFileSync(new URL('../apps_script/Bridge.gs',import.meta.url),'utf8'),context);
const seen = new Map();
context.PropertiesService = {getScriptProperties:()=>({getProperty:()=>secret})};
context.Utilities = {computeHmacSha256Signature:(p,s)=>[...createHmac('sha256',s).update(p).digest()].map(x=>x>127?x-256:x)};
context.CacheService = {getScriptCache:()=>({get:k=>seen.get(k),put:(k,v)=>seen.set(k,v)})};
context.LockService = {getScriptLock:()=>({waitLock(){},releaseLock(){}})};
context.ContentService = {MimeType:{JSON:'json'},createTextOutput:body=>({setMimeType(){return {body}}})};
context.Session = {getActiveUser:()=>({getEmail:()=>''})};
context.rows_ = name=>name==='05_OWNER_MASTER'?[{email:actor,role:'ADMIN',active:'YES'}]:[];
context.BRIDGE_ACTIONS.bootstrap = ()=>context.user_().email;
const envelope = (nonce=randomUUID(),action='bootstrap',args=[])=>{const payload=JSON.stringify({ts:Date.now(),nonce,actor,action,args});return {payload,signature:createHmac('sha256',secret).update(payload).digest('hex')};};
const post = value=>JSON.parse(context.doPost({postData:{contents:JSON.stringify(value)}}).body);
const signed = envelope();
assert.equal(post(signed).result,actor);
assert.match(post(signed).error,/already used/);
assert.match(post({...envelope(),signature:'0'.repeat(64)}).error,/Access denied/);
assert.match(post(envelope(randomUUID(),'setup')).error,/Unknown action/);
context.rows_ = ()=>[];
assert.match(post(envelope()).error,/Not authorized/);

let sent;
globalThis.fetch=async(url,options)=>{sent={url,...JSON.parse(options.body)};return {ok:true,text:async()=>JSON.stringify({ok:true,result:{email:actor}})};};
const request=(credential=token,action='bootstrap')=>({httpMethod:'POST',headers:{authorization:'Bearer '+credential},body:JSON.stringify({action,args:[]})});
assert.equal((await handler(request('bad'))).statusCode,401);
assert.equal((await handler(request(token,'setup'))).statusCode,400);
const result=await handler(request());
assert.equal(result.statusCode,200);
assert.deepEqual(JSON.parse(result.body).result,{email:actor});
assert.equal(sent.url,process.env.APPS_SCRIPT_WEBAPP_URL);
assert.equal(sent.signature,createHmac('sha256',secret).update(sent.payload).digest('hex'));
assert.equal(JSON.parse(sent.payload).actor,actor);
const html=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8');
assert.match(html,/lang="en"/);
assert.doesNotMatch(js,/google\.script\.run/);
assert.match(js,/chatgpt\.com\/\?q=/);
assert.match(js,/window\.open\(uri/);
console.log('Signed bridge, active admin, token and manual ChatGPT checks passed (mocked services).');
