import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {createHash,createHmac,randomUUID} from 'node:crypto';const root=new URL('../',import.meta.url);
export function runtime(){
 const ctx={console,Date};vm.createContext(ctx);
 for(const file of ['Code.gs','Migration.gs','AuthService.gs','OrderService.gs','CalendarService.gs','DocumentService.gs','GeoService.gs','PromptService.gs','ExportService.gs','WorkspaceService.gs','MetadataService.gs','TransferService.gs','Bridge.gs'])vm.runInContext(fs.readFileSync(new URL('apps_script/'+file,root),'utf8'),ctx,{filename:file});
 const tables={};for(const name of Object.keys(vm.runInContext('SCHEMA',ctx)))tables[name]=[];
 const clone=o=>JSON.parse(JSON.stringify(o));
 ctx.rows_=n=>clone(tables[n]||[]);ctx.add_=(n,o)=>{const schema=vm.runInContext('SCHEMA',ctx)[n];tables[n].push(Object.fromEntries(schema.map(k=>[k,o[k]??''])));};
 ctx.patch_=(n,id,o)=>{const schema=vm.runInContext('SCHEMA',ctx)[n],record=tables[n].find(x=>x[schema[0]]===id);if(!record)throw Error('Record not found '+n+' '+id);Object.assign(record,clone(o));};ctx.lock_=f=>f();
 const properties={DB_ID:'staging-only',ROOT_ID:'root',CALENDAR_ID:'eudr-calendar',BRIDGE_SECRET:'b'.repeat(64),ALLOWED_ORIGINS:'https://koda-eudr-system.netlify.app'};
 ctx.PropertiesService={getScriptProperties:()=>({getProperty:k=>properties[k]||'',setProperties:p=>Object.assign(properties,p)})};
 ctx.Session={getActiveUser:()=>({getEmail:()=>''}),getEffectiveUser:()=>({getEmail:()=> 'admin@test.example'})};
 let fileNo=0;const files=new Map(),folders=new Map();
 function blob(bytes,type='text/plain',name='file'){return {getBytes:()=>[...bytes],getContentType:()=>type,getDataAsString:()=>Buffer.from(bytes).toString(),getName:()=>name,setName(n){name=n;return this;}};}
 function folder(id,name=id){const children=[],contained=[];const f={getId:()=>id,getName:()=>name,getUrl:()=> 'https://drive.google.com/drive/folders/'+id,getFolders:()=>iterator(children),getFoldersByName:n=>iterator(children.filter(x=>x.getName()===n)),createFolder:n=>{const x=folder('folder-'+(++fileNo),n);children.push(x);return x;},getFilesByName:n=>iterator(contained.filter(x=>x.getName()===n)),createFile:b=>{const id='file-'+(++fileNo);let description='';const file={getId:()=>id,getName:()=>b.getName(),getBlob:()=>b,getSize:()=>b.getBytes().length,getDescription:()=>description,setDescription:d=>description=d};files.set(id,file);contained.push(file);return file;}};folders.set(id,f);return f;}
 function iterator(items){let i=0;return {hasNext:()=>i<items.length,next:()=>items[i++]};}folder('root');
 ctx.DriveApp={getFolderById:id=>{if(!folders.has(id))throw Error('Missing folder');return folders.get(id);},getFileById:id=>{if(!files.has(id))throw Error('Missing file');return files.get(id);}};
 ctx.Utilities={getUuid:randomUUID,DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,s)=>[...createHash('sha256').update(typeof s==='string'?s:Buffer.from(s)).digest()],computeHmacSha256Signature:(p,s)=>[...createHmac('sha256',s).update(p).digest()],base64Decode:s=>[...Buffer.from(s,'base64')],base64Encode:b=>Buffer.from(b).toString('base64'),newBlob:(bytes,type,name)=>blob(typeof bytes==='string'?[...Buffer.from(bytes)]:bytes,type,name),zip:bs=>blob([...Buffer.from(bs.map(b=>b.getName()+':'+b.getDataAsString()).join('\n'))],'application/zip','zip')};
 const seen=new Map();ctx.CacheService={getScriptCache:()=>({get:k=>seen.get(k),put:(k,v)=>seen.set(k,v)})};ctx.LockService={getScriptLock:()=>({waitLock(){},releaseLock(){}})};ctx.ContentService={MimeType:{JSON:'json'},createTextOutput:body=>({setMimeType:()=>({body})})};
 const events=new Map();let insertions=0;ctx.Calendar={Events:{get:(cal,id)=>{if(!events.has(id))throw Error('404 not found');return clone(events.get(id));},list:()=>({items:[]}),insert:(body,cal)=>{assert.equal(cal,'eudr-calendar');insertions++;events.set(body.id,clone(body));return body;},patch:(body,cal,id)=>{assert.equal(cal,'eudr-calendar');events.set(id,clone(body));return body;}}};
 const explicitCaps=JSON.stringify(vm.runInContext('CAPABILITIES_',ctx));
 const admin={capabilities:explicitCaps,email:'admin@test.example',name:'Admin',role:'ADMIN',active:'YES'},a={email:'a@supplier.example',role:'SUPPLIER_USER',active:'YES',supplier_id:'sa'},b={email:'b@supplier.example',role:'SUPPLIER_USER',active:'YES',supplier_id:'sb'};
 tables['05_OWNER_MASTER']=[admin,a,b,{capabilities:explicitCaps,email:'review@test.example',role:'EUDR_REVIEWER',active:'YES',assigned_orders:'["ca"]'}];tables['14_SUPPLIERS']=[{id:'sa',name:'Supplier A',active:'YES'},{id:'sb',name:'Supplier B',active:'YES'}];
 function actor(email=admin.email,action='uploadEvidence',key=randomUUID(),args=[]){ctx.BRIDGE_ACTOR=email;ctx.BRIDGE_REQUEST_KEY=key;ctx.BRIDGE_ACTION=action;ctx.BRIDGE_ARGS=args;}
 function seed(){tables['01_SO_MASTER']=[{id:'ca',so:'SO-A',owner:admin.email,folder:'root',status:'COLLECTING_EVIDENCE'},{id:'cb',so:'SO-B',owner:admin.email,folder:'root'}];tables['02_SO_ITEM_MATERIAL']=[{id:'ma',case_id:'ca',material:'Walnut',folder:'root'},{id:'mb',case_id:'cb',material:'MDF',folder:'root'}];tables['04_EVIDENCE_TRACKER']=[{id:'ta',case_id:'ca',material_id:'ma',supplier_id:'sa',owner:a.email,evidence:'INV',evidence_block:'01_Commercial_Shipping',required:'YES',status:'MISSING',due:'2026-10-09',assigned_reviewer:'review@test.example'},{id:'tb',case_id:'cb',material_id:'mb',supplier_id:'sb',owner:b.email,status:'MISSING'}];}
 actor();return {ctx,tables,actor,seed,files,folders,properties,events,get insertions(){return insertions;}};
}
