import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';
function setup(){const dom=new JSDOM(fs.readFileSync('public/index.html','utf8'),{url:'https://staging.example',runScripts:'outside-only'}),w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.URL.revokeObjectURL=()=>{};w.fetch=async()=>({json:async()=>({ok:true,data:[]})});w.eval(fs.readFileSync('public/i18n.js','utf8'));w.eval(fs.readFileSync('public/app.js','utf8').replace('\nload();','\n')+`\nstate={user:{email:'test',role:'MARKETING',capabilities:['ORDER_EDIT','SO_VIEW','MATERIAL_EDIT','CHAIN_EDIT','SUPPLIER_EDIT','AI_USE','POLICY_EDIT','WORKFLOW_CLOSE','EVIDENCE_REVIEW','GEO_EDIT']},cases:[{id:'c',so:'SO-TEST',customer:'TEST',po:'PO',issues:[],status:'COLLECTING_EVIDENCE'}],products:[{id:'p1',case_id:'c',product_name:'Chair',quantity:2,active:'YES'},{id:'p2',case_id:'c',product_name:'Table',quantity:1,active:'YES'}],materials:[{id:'m',case_id:'c',material:'Walnut'}],tasks:[],docs:[],suppliers:[],chain:[],geo:[],requirements:[],owners:[]};selected='c';window.testState=state;call=async()=>[];`);return w;}
test('workspace keeps products, four evidence blocks and final review in order without an early consolidated warning',()=>{
 const w=setup();
 w.eval("testState.products[0].product_name='<img src=x onerror=alert(1)>';testState.cases[0].issues=['UPSTREAM_CHAIN_MISSING'];testState.tasks=[{id:'t1',case_id:'c',material_id:'m',evidence:'Invoice',evidence_block:'01_Commercial_Shipping',status:'MISSING',required:'YES'},{id:'t2',case_id:'c',material_id:'m',evidence:'FSC',evidence_block:'02_FSC_Certification',status:'APPROVED',required:'YES'}];workspace();bind();");
 assert.equal(w.document.querySelectorAll('[data-product]').length,2);
 assert.equal(w.document.querySelector('[onerror]'),null);
 const blocks=[...w.document.querySelectorAll('[data-evidence-block]')];
 assert.deepEqual(blocks.map(b=>b.dataset.evidenceBlock),['01_Commercial_Shipping','02_FSC_Certification','03_Transport','04_Geolocation']);
 assert.ok(blocks[0].querySelector('.evidence-state--missing'));
 assert.ok(blocks[1].querySelector('.evidence-state--approved'));
 assert.equal(w.document.querySelectorAll('[data-action="addRequirement"]').length,4);
 assert.ok(blocks[0].querySelector('[data-action="taskRequirement"]'));
 assert.equal(w.document.querySelector('.workspace-summary').textContent.includes('UPSTREAM_CHAIN_MISSING'),false);
 const buttons=[...w.document.querySelectorAll('[data-action]')].map(b=>b.dataset.action);
 assert.ok(buttons.indexOf('aiOutputs')<buttons.indexOf('finalReview'));
 assert.ok(blocks[3].compareDocumentPosition(w.document.querySelector('.dossier-step'))&w.Node.DOCUMENT_POSITION_FOLLOWING);
});
test('scoped requirement form offers material and tier decisions without changing global policy',()=>{
 const w=setup();w.eval("testState.tasks=[{id:'t1',case_id:'c',material_id:'m',evidence:'Invoice',required:'YES',status:'MISSING'}];testState.chain=[{id:'n1',material_id:'m',display_name:'Mill',tier:1}];taskRequirementDialog('t1')");
 assert.ok(w.document.querySelector('#taskRequirementForm [value="NOT_REQUIRED"]'));
 assert.ok(w.document.querySelector('#taskRequirementForm textarea[required]'));
 w.eval("scopedRequirementDialog('m','01_Commercial_Shipping')");
 assert.ok(w.document.querySelector('#scopedRequirementForm [value="n1"]'));
});
test('optional evidence remains uploadable and shows its workflow status',()=>{
 const w=setup();w.eval("testState.user.capabilities.push('EVIDENCE_UPLOAD');testState.tasks=[{id:'t1',case_id:'c',material_id:'m',evidence:'Optional invoice',required:'NO',override_state:'OPTIONAL',status:'MISSING'}];workspace()");
 assert.ok(w.document.querySelector('[data-action="upload"][data-id="t1"]'));
 assert.ok(w.document.querySelector('.evidence-state--missing'));
 assert.ok(w.document.querySelector('.evidence-state--not-required'));
});
test('final dossier modal shows backend blockers and gates closure',async()=>{
 const w=setup();
 w.eval("call=async()=>({ready:false,blockers:[{code:'UPSTREAM_CHAIN_MISSING',details:'Walnut'}]})");
 await w.eval("finalDossier('c')");
 assert.ok(w.document.querySelector('[role="alert"]').textContent.includes('UPSTREAM CHAIN MISSING'));
 assert.equal(w.document.querySelector('#closeOrderForm'),null);
 w.eval("call=async()=>({ready:true,blockers:[]})");
 await w.eval("finalDossier('c')");
 assert.ok(w.document.querySelector('#closeOrderForm textarea[required]'));
});
test('Admin without explicit grants can see New Order in the UI',()=>{
 const w=setup();w.eval("testState.user={email:'admin',role:'ADMIN',capabilities:['ORDER_EDIT','SO_VIEW','MATERIAL_EDIT','WORKFLOW_CLOSE']};dashboard();");
 assert.ok(w.document.querySelector('[data-action="newOrder"]'));
});
test('new order supports add/remove products and optional image preview controls',()=>{const w=setup();w.eval('newOrder()');assert.equal(w.document.querySelectorAll('.new-product').length,1);w.document.querySelector('#addProduct').click();assert.equal(w.document.querySelectorAll('.new-product').length,2);w.document.querySelector('.new-product button').click();assert.equal(w.document.querySelectorAll('.new-product').length,1);assert.ok(w.document.querySelector('input[name="product_image"]'));assert.ok(w.document.querySelector('#orderForm').textContent.includes('3 MB'));});
test('MP Material, policy and supplier forms use backend action-compatible fields',()=>{const w=setup();w.eval("materialsDialog('c')");assert.ok(w.document.querySelector('[name="supplier_po"]'));assert.equal(w.document.querySelectorAll('[name="product"]').length,2);w.eval('policyDialog()');assert.ok(w.document.querySelector('[name="rule_version"]'));w.eval("supplierForm('')");assert.ok(w.document.querySelector('[name="supplier_code"]'));});
test('Vietnamese labels work and MATERIAL_EXTRACTION is absent from prompt menu',()=>{const w=setup();w.eval("window.EudrI18n.setLanguage('vi');workspace();promptStudio();");assert.equal(w.EudrI18n.t('AI Review Outputs'),'Kết quả kiểm tra AI');assert.equal(w.document.querySelector('[value="MATERIAL_EXTRACTION"]'),null);});
test('prompt identifies source and provides Drive and authorized download actions',async()=>{const w=setup();w.eval("call=async()=>({id:'run',prompt:'PROMPT',context:{order:'SO-TEST',selected_documents:[{document_id:'doc1',name:'Supplier_PO.pdf',version:1,file_url:'https://drive.google.com/file/d/file-real/view'}]}})");await w.eval("showPrompt('c','PRICE_REDACTION','doc1')");const panel=w.document.querySelector('.context-panel');assert.ok(panel.textContent.includes('Supplier_PO.pdf'));assert.ok(panel.textContent.includes('doc1'));assert.equal(panel.querySelector('a[href="https://drive.google.com/file/d/file-real/view"]')?.textContent,'Open Source File');assert.ok(panel.querySelector('button'));assert.ok(w.document.querySelector('#promptText').value.includes('PROMPT'));});
test('AI Assistant offers originals and verified redactions for translation without re-upload',async()=>{const w=setup();w.eval("testState.docs=[{id:'original',case_id:'c',kind:'EVIDENCE',name:'Forest.pdf',status:'APPROVED',active_version:'YES'},{id:'red',case_id:'c',kind:'REDACTED',name:'Forest_red.pdf',status:'APPROVED',active_version:'YES',redaction_verified:'YES'},{id:'pending',case_id:'c',kind:'REDACTED',name:'Pending.pdf',status:'UPLOADED',active_version:'YES',redaction_verified:'NO'}];promptStudio()");w.document.querySelector('[name="promptFunction"]').value='ENGLISH_SUBTITLE';w.document.querySelector('[name="promptFunction"]').dispatchEvent(new w.Event('change'));assert.deepEqual([...w.document.querySelectorAll('[name="promptDocument"] option')].map(o=>o.value),['original','red']);w.eval("call=async()=>({id:'run',prompt:'PROMPT',context:{order:'SO-TEST',selected_documents:[{document_id:'red',name:'Forest_red.pdf',file_url:'https://drive.google.com/file/d/red-file/view'}],ai_output_folders:{root:'https://drive.google.com/drive/folders/root',ENGLISH_SUBTITLE:'https://drive.google.com/drive/folders/subtitle'}}})");await w.eval("showPrompt('c','ENGLISH_SUBTITLE','red')");assert.equal(w.document.querySelector('#registerPromptPdf'),null);assert.match(w.document.querySelector('#importResult').textContent,/Open View AI Results/);assert.ok(w.document.querySelector('.context-panel a[href="https://drive.google.com/drive/folders/subtitle"]'));assert.equal(w.document.querySelector('#importAi').hidden,true);});
test('AI output panel distinguishes a registered external PDF from a prompt run awaiting structured result',async()=>{const w=setup();w.eval("call=async(action)=>action==='syncAIOutputs'?{registered:['external'],errors:[]}:{runs:[{id:'run1',case_id:'c',document_id:'source',function:'PRICE_REDACTION',prompt_version:'3.3.0',result_status:'AWAITING_RESULT'},{id:'conditional',case_id:'c',document_id:'source',function:'PRICE_REDACTION',prompt_version:'3.3.0',result_status:'CONDITIONAL_AWAITING_PRICE_DECISION'}],findings:[],documents:[{id:'external',case_id:'c',kind:'AI_OUTPUT',ai_output_type:'PRICE_REDACTION',source_document_id:'source',prompt_run_id:'run1',name:'INV_redacted.pdf',status:'PENDING_REVIEW',redaction_verified:'NO'}]}");await w.eval("aiOutputs('c')");
 assert.match(w.document.querySelector('#drawer summary').textContent,/PDF REGISTERED · PENDING_REVIEW/);
 assert.ok(w.document.querySelector('#drawer [data-action="document"][data-id="external"]'));
 assert.match(w.document.querySelector('#drawer').textContent,/Drive output/);assert.equal(w.document.querySelector('#drawer [data-action="registerExternal"]'),null);
 assert.equal(w.document.querySelector('#drawer [data-action="verifyProcessed"]'),null);
 assert.equal(w.testState.docs.find(d=>d.id==='external')?.kind,'AI_OUTPUT');
 assert.equal(w.document.querySelectorAll('#drawer summary').length,1);
});
test('material and supplier selection scopes four evidence blocks; relationship and evidence actions sit at section end',()=>{
 const w=setup();w.eval("testState.materials.push({id:'m2',case_id:'c',material:'Beech'});testState.chain=[{id:'n1',case_id:'c',material_id:'m',display_name:'Mill A',tier:1,supplier_id:'sa'},{id:'n2',case_id:'c',material_id:'m2',display_name:'Mill B',tier:1,supplier_id:'sb'}];testState.tasks=[{id:'order',case_id:'c',evidence:'Sales order',evidence_block:'01_Commercial_Shipping',document_id:'d-so',status:'APPROVED'},{id:'legacy-so',case_id:'c',material_id:'m',chain_node_id:'n1',evidence:'Sales order',evidence_block:'01_Commercial_Shipping',document_id:'d-so',status:'APPROVED'},{id:'a',case_id:'c',material_id:'m',chain_node_id:'n1',evidence:'FSC Cert',evidence_block:'02_FSC_Certification',status:'MISSING'},{id:'b',case_id:'c',material_id:'m2',chain_node_id:'n2',evidence:'INV',evidence_block:'01_Commercial_Shipping',status:'MISSING'}];workspace();bind();");
 assert.equal(w.document.querySelectorAll('.workspace-data-section').length,3);
 assert.ok(w.document.querySelector('.workspace-data-section:last-child [data-action="addRelationship"]'));
 assert.ok(w.document.querySelector('.workspace-data-section:nth-child(2) .workspace-actions [data-action="materialInfo"]'));
 assert.equal(w.document.querySelectorAll('.evidence-block').length,4);
 assert.ok(w.document.querySelector('.evidence-block').textContent.includes('Sales Order (Customer → KODA)'));
 w.document.querySelector('[data-chain-node="n1"]').click();
 assert.ok(!w.document.querySelector('.evidence-block').textContent.includes('Sales Order (Customer → KODA)'));
 assert.equal(w.document.querySelector('[data-action="document"][data-id="d-so"]'),null);
 assert.ok(w.document.querySelector('[data-evidence-block="02_FSC_Certification"]').textContent.includes('FSC Cert'));
 assert.equal(w.document.querySelectorAll('[data-evidence-block="01_Commercial_Shipping"] [data-action="document"]').length,0);
 assert.equal(w.document.querySelectorAll('[data-evidence-block]').length,4);
 assert.equal(w.document.querySelector('[data-evidence-block="05_Upstream_Traceability"]'),null);
 assert.ok(w.document.querySelector('.dossier-step'));
 w.document.querySelector('[data-material="m2"]').click();
 assert.equal(w.document.querySelector('[data-chain-node="n1"]'),null);
 assert.ok(w.document.querySelector('[data-chain-node="n2"]'));
 w.document.querySelector('[data-chain-node="n2"]').click();
 assert.ok(w.document.querySelector('[data-evidence-block="01_Commercial_Shipping"]').textContent.includes('INV'));
});
test('order image sits in the green header and section actions use compact menus',()=>{const w=setup();w.eval("testState.chain=[{id:'n1',case_id:'c',material_id:'m',supplier_id:'sa',display_name:'Supplier A',node_type:'SUPPLIER',tier:1}];testState.suppliers=[{id:'sa',name:'Supplier A',active:'YES'},{id:'sb',name:'Supplier B',active:'YES'}];workspace();bind();");w.document.querySelector('[data-chain-node="n1"]').click();
 assert.ok(w.document.querySelector('.workspace-summary > #productPreview'));
 assert.equal(w.document.querySelector('.workspace-data #productPreview'),null);
 assert.equal(w.document.querySelector('[data-action="materials"]').textContent,'+ Add Materials');
 assert.equal(w.document.querySelector('[data-action="addRelationship"]').textContent,'+ Add Relationship');
 assert.ok(w.document.querySelector('.workspace-data-section:nth-child(2) details.action-menu [data-action="materialEdit"]'));
 assert.ok(w.document.querySelector('.workspace-data-section:nth-child(3) details.action-menu [data-action="chainEdit"]'));
 w.document.querySelector('[data-action="chainEdit"]').click();
 assert.equal(w.document.querySelector('#chainEditForm [name="supplier_id"] option[value="sb"]').textContent.trim(),'Supplier B');
});
test('product edit, image and remove live only in the arrow left of Add Product for the selected product',()=>{const w=setup();w.eval('workspace();bind();');
 assert.equal(w.document.querySelectorAll('.product-row [data-action]').length,0);
 const menu=()=>w.document.querySelector('.workspace-data-section:first-child details.action-menu');
 assert.equal(menu().open,false);
 assert.equal(menu().nextElementSibling.dataset.action,'productEdit');
 assert.equal(menu().nextElementSibling.textContent,'+ Add Product');
 assert.deepEqual([...menu().querySelectorAll('.action-menu-group:first-child [data-action]')].map(b=>b.dataset.action),['productEdit','productImage','removeProduct']);
 assert.deepEqual([...menu().querySelectorAll('.action-menu-group:first-child [data-action]')].map(b=>b.dataset.id),['p1','p1','p1']);
 menu().querySelector('summary').click();assert.equal(menu().open,true);
 w.document.querySelector('[data-product="p2"]').click();
 assert.deepEqual([...menu().querySelectorAll('.action-menu-group:first-child [data-action]')].map(b=>b.dataset.id),['p2','p2','p2']);
 assert.equal(w.document.querySelector('.workspace-data-section:nth-child(2) [data-action="productImage"]'),null);
 w.eval("testState.materials=[];workspace();bind();");assert.ok(menu().querySelector('[data-action="productImage"][data-id="p2"]'));
});
test('Orders title derives every active SO product in sequence and search finds later products',()=>{const w=setup();w.eval("testState.cases[0].product='Chair';testState.products=[{id:'p2',case_id:'c',product_name:'Second Table',sequence:2,active:'YES'},{id:'p3',case_id:'c',product_name:'Old Name',sequence:3,active:'NO'},{id:'p1',case_id:'c',product_name:'First Chair',sequence:1,active:'YES'}];orders();bind();");
 assert.equal(w.document.querySelector('.order-board .order-copy strong').textContent,'SO-TEST – First Chair, Second Table');
 assert.equal(w.document.querySelector('.order-board').textContent.includes('Old Name'),false);
 w.document.querySelector('#quickSearch').value='Second Table';w.document.querySelector('#quickSearch').dispatchEvent(new w.Event('input',{bubbles:true}));
 assert.equal(w.document.querySelectorAll('.order-board .order-item').length,1);
 w.eval('workspace()');assert.equal(w.document.querySelector('.workspace-summary h2').textContent,'SO-TEST – First Chair, Second Table');
});
test('My Tasks uses two columns with role scope, while Admin sees all',()=>{
 const w=setup();w.eval("testState.user={email:'p@test.example',role:'PURCHASING',department:'Purchasing',capabilities:['EVIDENCE_UPLOAD']};testState.tasks=[{id:'mine',case_id:'c',material_id:'m',owner:'p@test.example',department:'Purchasing',evidence:'PO',status:'MISSING',due:'2026-10-01'},{id:'review',case_id:'c',material_id:'m',owner:'other@test.example',assigned_reviewer:'p@test.example',evidence:'INV',status:'SUBMITTED',due:'2026-10-08'},{id:'other',case_id:'c',material_id:'m',owner:'m@test.example',department:'Marketing',evidence:'FSC',status:'MISSING',due:'2026-10-08'}];myTasks();");
 assert.equal(w.document.querySelectorAll('.task-columns > div').length,2);
 assert.ok(w.document.querySelector('.task-columns').textContent.includes('PO'));
 assert.ok(w.document.querySelector('.task-columns').textContent.includes('INV'));
 assert.ok(!w.document.querySelector('.task-columns').textContent.includes('FSC'));
 w.eval("testState.user.role='ADMIN';myTasks()");assert.ok(w.document.querySelector('.task-columns').textContent.includes('FSC'));
});
test('Calendar shows role-scoped dated task count and opens that date details',()=>{
 const w=setup();w.eval("testState.user={email:'p@test.example',role:'PURCHASING',department:'Purchasing',capabilities:['EVIDENCE_UPLOAD']};testState.tasks=[{id:'mine',case_id:'c',material_id:'m',owner:'p@test.example',evidence:'Invoice',status:'MISSING',due:'2026-10-08'},{id:'other',case_id:'c',material_id:'m',owner:'m@test.example',evidence:'FSC',status:'MISSING',due:'2026-10-08'}];month=new Date(2026,9,1);calendar();bind();");
 const day=w.document.querySelector('[data-calendar-day="2026-10-08"]');assert.ok(day);assert.match(day.textContent,/1 task/);day.click();
 assert.ok(w.document.querySelector('#drawer').open);assert.ok(w.document.querySelector('#drawer').textContent.includes('Invoice'));assert.ok(!w.document.querySelector('#drawer').textContent.includes('FSC'));
});
test('Export separates original and verified AI documents, then offers a direct ZIP download',async()=>{
 const w=setup();w.eval("testState.docs=[{id:'d1',case_id:'c',kind:'EVIDENCE',name:'INV.pdf',version:1,status:'APPROVED',active_version:'YES'},{id:'d2',case_id:'c',kind:'REDACTED',name:'INV_redacted.pdf',version:1,status:'APPROVED',active_version:'YES',redaction_verified:'YES'},{id:'d3',case_id:'c',kind:'EN_SUBTITLE',name:'unverified.pdf',version:1,status:'UPLOADED',active_version:'YES'}];call=async()=>({packages:[{case_id:'c',name:'SO-TEST.zip',download_id:'export:e1',size_bytes:4500000}],errors:[]});exports();");
 assert.equal(w.document.querySelectorAll('.export-column').length,2);
 assert.equal(w.document.querySelectorAll('.export-column:first-child input:checked').length,1);
 assert.equal(w.document.querySelectorAll('.export-column:last-child input:checked').length,1);
 assert.ok(w.document.querySelector('.export-column:last-child input[value="d3"]:disabled'));
 w.document.querySelector('#exportSelected').click();await new Promise(resolve=>setImmediate(resolve));
 assert.ok(w.document.querySelector('#drawer').open);assert.ok(w.document.querySelector('[data-download-export]'));
 assert.ok(w.document.querySelector('#exportResult').textContent.includes('SO-TEST.zip'));
});
test('Export selects multiple orders and sends one request with scoped document selections',async()=>{const w=setup();w.eval("testState.cases.push({id:'c2',so:'SO-SECOND'});testState.docs=[{id:'d1',case_id:'c',kind:'EVIDENCE',name:'A.pdf',version:1,status:'APPROVED',active_version:'YES'},{id:'d2',case_id:'c2',kind:'EVIDENCE',name:'B.pdf',version:1,status:'APPROVED',active_version:'YES'}];window.exportCalls=[];call=async(action,input)=>{exportCalls.push({action,input});return {packages:input.orders.map((o,i)=>({case_id:o.case_id,name:'package'+i+'.zip',download_id:'export:'+i,size_bytes:100})),errors:[]}};exports();");const second=w.document.querySelector('[name="exportOrder"][value="c2"]');second.checked=true;second.dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.export-order-section').length,2);w.document.querySelector('#exportSelected').click();await new Promise(resolve=>setImmediate(resolve));assert.equal(w.exportCalls[0].action,'exportPackages');assert.deepEqual(JSON.parse(JSON.stringify(w.exportCalls[0].input.orders)),[{case_id:'c',document_ids:['d1']},{case_id:'c2',document_ids:['d2']}]);assert.equal(w.document.querySelectorAll('[data-download-export]').length,2);});
