const MAX_FILE_BYTES_=3000000;
function validateFile_(file){
 if(!file||typeof file.data!=='string'||!file.data||!/^[A-Za-z0-9+/]+={0,2}$/.test(file.data))fail_('INVALID_FILE','Invalid base64 file');
 if(file.data.length>Math.ceil(MAX_FILE_BYTES_*4/3)+8)fail_('FILE_TOO_LARGE','File must be less than 3 MB');
 const bytes=Utilities.base64Decode(file.data),type=file.type,name=fileName_(file.name);if(bytes.length>=MAX_FILE_BYTES_)fail_('FILE_TOO_LARGE','File must be less than 3 MB');if(!bytes.length)fail_('INVALID_FILE','Empty file');
 const hex=bytes.slice(0,8).map(b=>('0'+((b+256)%256).toString(16)).slice(-2)).join('');
 const signatures={'application/pdf':'255044462d','image/png':'89504e470d0a1a0a','image/jpeg':'ffd8ff'};
 if(signatures[type]){if(!hex.startsWith(signatures[type]))fail_('INVALID_FILE','Content does not match file type');}
 else if(type==='image/webp'){if(hex.slice(0,8)!=='52494646'||bytes.slice(8,12).map(b=>String.fromCharCode(b)).join('')!=='WEBP')fail_('INVALID_FILE','Invalid WebP signature');}
 else if(['application/json','application/geo+json'].includes(type)){try{JSON.parse(Utilities.newBlob(bytes).getDataAsString());}catch(e){fail_('INVALID_FILE','Malformed JSON file');}}
 else fail_('INVALID_FILE','Supported in this staging release: PDF, PNG, JPG, JSON and GeoJSON');
 const extensions={'application/pdf':/\.pdf$/i,'image/png':/\.png$/i,'image/jpeg':/\.jpe?g$/i,'image/webp':/\.webp$/i,'application/json':/\.json$/i,'application/geo+json':/\.(geo)?json$/i};
 if(!extensions[type]||!extensions[type].test(name))fail_('INVALID_FILE','Extension does not match MIME');
 return {bytes,type,name};
}
function storeFile_(folder,key,file,name){
 const marker='KODA_EUDR_RECORD:'+key,it=folder.getFilesByName(name);let found=null,occupied=false;
 while(it.hasNext()){const f=it.next();if(f.getDescription()===marker){if(found)fail_('VERSION_CONFLICT','Duplicate file record');found=f;}else occupied=true;}
 if(found)return found;if(occupied)fail_('VERSION_CONFLICT','Filename is occupied by an unregistered file; resolve before retry');
 const created=folder.createFile(Utilities.newBlob(file.bytes,file.type,name));created.setDescription(marker);return created;
}
function uploadEvidence(taskId,file){const u=requireCapability_('EVIDENCE_UPLOAD');let t=task_(taskId,u);if(t.evidence==='Sales order')fail_('PERMISSION_DENIED','Sales Order is registered at order level');
 const valid=validateFile_(file);return withOperation_(()=>{
 t=task_(taskId,u);if(!['MISSING','DRAFT','UPLOADED','REJECTED','MORE_INFO_REQUIRED'].includes(t.status))fail_('VERSION_CONFLICT','Evidence is submitted or approved; reviewer must return it first');const m=rows_('02_SO_ITEM_MATERIAL').find(x=>x.id===t.material_id),id=stable_('document:'+taskId+':'+BRIDGE_REQUEST_KEY),all=rows_('06_DOCUMENT_REGISTER').filter(d=>d.task_id===taskId&&d.kind==='EVIDENCE'),existing=all.find(d=>d.id===id),version=existing?Number(existing.version):Math.max(0,...all.map(d=>Number(d.version)||0))+1;
 if(!m)fail_('INVALID_INPUT','Task material missing');const active=all.find(d=>d.id===t.document_id);if(active&&['DRAFT','UPLOADED'].includes(active.status)&&active.uploaded_by!==u.email)fail_('PERMISSION_DENIED','Only uploader can replace the active draft');if(!existing&&file.expected_document_id!==String(t.document_id||''))fail_('VERSION_CONFLICT','Task document changed; refresh before uploading');
 if(t.status==='APPROVED'&&!existing)fail_('VERSION_CONFLICT','Request revision before replacing approved evidence');
 const supplier=rows_('14_SUPPLIERS').find(s=>s.id===t.supplier_id),ext=valid.type==='application/pdf'?'pdf':valid.type==='image/png'?'png':valid.type==='image/jpeg'?'jpg':'geojson';
 const name=fileName_((supplier?supplier.name:'KODA')+'_'+t.evidence+'_v'+String(version).padStart(2,'0')+'.'+ext),f=storeFile_(evidenceFolder_(t,m),id,valid,name);
 if(!existing)add_('06_DOCUMENT_REGISTER',{id,case_id:t.case_id,task_id:taskId,kind:'EVIDENCE',name,file_id:f.getId(),version,status:'UPLOADED',uploaded_by:u.email,created_at:now_(),material_id:m.id,supplier_id:t.supplier_id,chain_node_id:t.chain_node_id||'',file_size_bytes:valid.bytes.length,sha256:bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,valid.bytes)),evidence_block:t.evidence_block,document_type:t.evidence,mime_type:valid.type,active_version:'YES',updated_at:now_(),request_key:BRIDGE_REQUEST_KEY});
 all.filter(d=>d.id!==id&&d.active_version==='YES').forEach(d=>patch_('06_DOCUMENT_REGISTER',d.id,{active_version:'NO',superseded_by:id,updated_at:now_()}));
 patch_('04_EVIDENCE_TRACKER',taskId,{document_id:id,status:'UPLOADED',updated_at:now_()});patch_('01_SO_MASTER',t.case_id,{status:'IN_REVIEW',updated_at:now_()});
 notify_(t.assigned_reviewer,t.case_id,id,'New evidence uploaded for review');audit_('DOCUMENT_UPLOADED',t.case_id,id,t.document_id||'',JSON.stringify({version,status:'UPLOADED'}),u.email);return {id,version};
 });}
function submitDocument(id){const u=requireCapability_('EVIDENCE_UPLOAD');return lock_(()=>{const d=document_(id,u);if(d.active_version!=='YES'||d.status!=='UPLOADED')fail_('VERSION_CONFLICT','Only active uploaded version can be submitted');patch_('06_DOCUMENT_REGISTER',id,{status:'SUBMITTED',submitted_at:now_(),updated_at:now_()});if(d.task_id)patch_('04_EVIDENCE_TRACKER',d.task_id,{status:'SUBMITTED',submitted_at:now_(),updated_at:now_()});audit_('DOCUMENT_SUBMITTED',d.case_id,id,'UPLOADED','SUBMITTED',u.email);return true;});}
function reviewDocument(id,decision,comment){const u=requireCapability_('EVIDENCE_REVIEW');return lock_(()=>{
 const d=document_(id,u);if(!['EVIDENCE','SO'].includes(d.kind))fail_('INVALID_INPUT','Use processed-copy verification for derivatives');if(d.task_id)task_(d.task_id,u);if(d.active_version!=='YES')fail_('VERSION_CONFLICT','Inactive version cannot be reviewed');
 if(!['IN_REVIEW','APPROVED','REJECTED','MORE_INFO_REQUIRED'].includes(decision))fail_('INVALID_INPUT','Invalid review decision');
 if(!['SUBMITTED','IN_REVIEW','APPROVED'].includes(d.status))fail_('VERSION_CONFLICT','Submit document before review');
 const note=text_(comment||'',2000);if(['REJECTED','MORE_INFO_REQUIRED'].includes(decision)&&!note)fail_('INVALID_INPUT','Comment required');
 const linkedTasks=rows_('04_EVIDENCE_TRACKER').filter(t=>t.document_id===id);if(linkedTasks.some(t=>!canTask_(u,t)))fail_('PERMISSION_DENIED','Linked review task outside scope');
 const o={status:decision,reviewed_by:u.email,reviewed_at:now_(),review_comment:note,updated_at:now_()};patch_('06_DOCUMENT_REGISTER',id,o);
 rows_('04_EVIDENCE_TRACKER').filter(t=>t.document_id===id).forEach(t=>{if(!canTask_(u,t))fail_('PERMISSION_DENIED','Linked review task outside scope');patch_('04_EVIDENCE_TRACKER',t.id,{status:decision,note,updated_at:now_()});notify_(t.owner,d.case_id,id,'Evidence '+decision+(note?': '+note:''));syncTaskCalendar_({...t,status:decision});});
 if(note)add_('16_COMMENTS',{id:uid_(),case_id:d.case_id,document_id:id,version:d.version,visibility:'SHARED_WITH_SUPPLIER',comment:note,author:u.email,created_at:now_()});
 audit_('DOCUMENT_'+decision,d.case_id,id,JSON.stringify({status:d.status,version:d.version}),JSON.stringify(o),u.email);return true;
 });}
function addComment(id,input){const u=user_();requireWrite_(u);const d=document_(id,u),visibility=input.visibility;
 if(!['INTERNAL_ONLY','SHARED_WITH_SUPPLIER'].includes(visibility)||u.role==='SUPPLIER_USER'&&visibility!=='SHARED_WITH_SUPPLIER')fail_('PERMISSION_DENIED','Comment visibility not allowed');
 const comment=text_(input.comment,3000);if(!comment)fail_('INVALID_INPUT','Comment required');return withOperation_(()=>{const cid=stable_('comment:'+BRIDGE_REQUEST_KEY+':'+u.email);if(!rows_('16_COMMENTS').some(c=>c.id===cid))add_('16_COMMENTS',{id:cid,case_id:d.case_id,document_id:id,version:d.version,visibility,comment,author:u.email,created_at:now_()});audit_('COMMENT_ADDED',d.case_id,cid,'',visibility,u.email);return {id:cid};});}
function getDocument(id){const u=user_();if(String(id).startsWith('export:'))return getExport_(String(id).slice(7),u);const d=document_(id,u),f=DriveApp.getFileById(d.file_id);if(f.getSize()>MAX_TRANSFER_)fail_('FILE_TOO_LARGE','File exceeds 25 MiB transfer limit');const blob=f.getSize()<=MAX_FILE_BYTES_?f.getBlob():null;
 const comments=rows_('16_COMMENTS').filter(c=>c.document_id===id&&(u.role!=='SUPPLIER_USER'||c.visibility==='SHARED_WITH_SUPPLIER'));
 const versions=rows_('06_DOCUMENT_REGISTER').filter(x=>x.case_id===d.case_id&&x.task_id===d.task_id&&x.kind===d.kind&&(!d.product_id||x.product_id===d.product_id)&&documentVisible_(x,u)&&(!['REDACTED','EN_SUBTITLE'].includes(d.kind)||x.source_document_id===d.source_document_id)).filter(x=>u.role!=='SUPPLIER_USER'||x.supplier_id===u.supplier_id).map(x=>({id:x.id,name:x.name,version:x.version,status:x.status,active_version:x.active_version,created_at:x.created_at,reviewed_at:x.reviewed_at}));
 return {id,name:d.name,type:d.mime_type||(blob?blob.getContentType():'application/pdf'),data:blob?Utilities.base64Encode(blob.getBytes()):null,download_chunked:!blob,size:f.getSize(),status:d.status,version:d.version,active:d.active_version,comments,versions};
}
function uploadProcessed(sourceId,kind,file){const u=requireCapability_('AI_USE'),d=document_(sourceId,u);if(file&&typeof file.data==='string'&&file.data.length>=4000000)fail_('OUTPUT_SIZE_BLOCKED','Derived PDF must be below 3 MB');const valid=validateFile_(file);if(!['REDACTED','EN_SUBTITLE'].includes(kind)||valid.type!=='application/pdf')fail_('INVALID_INPUT','Processed output must be PDF');validateDerivedLineage_(d,kind,file);return withOperation_(()=>{
 const id=stable_('processed:'+sourceId+':'+BRIDGE_REQUEST_KEY),c=order_(d.case_id,u),previous=rows_('06_DOCUMENT_REGISTER').filter(x=>x.source_document_id===sourceId&&x.kind===kind),old=previous.find(x=>x.id===id),version=old?Number(old.version):Math.max(0,...previous.map(x=>Number(x.version)||0))+1,name=fileName_(d.name.replace(/\.pdf$/i,'')+'_'+kind+'_v'+String(version).padStart(2,'0')+'.pdf'),f=storeFile_(aiOutputFolder_(c,kind),id,valid,name);
 if(!old)add_('06_DOCUMENT_REGISTER',{id,case_id:d.case_id,task_id:d.task_id,material_id:d.material_id,supplier_id:d.supplier_id,kind,name,file_id:f.getId(),chain_node_id:d.chain_node_id||'',ai_output_type:kind,prompt_run_id:file.prompt_run_id,file_size_bytes:valid.bytes.length,sha256:bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,valid.bytes)),validation_report:JSON.stringify(file.validation_report),version,status:'UPLOADED',uploaded_by:u.email,created_at:now_(),mime_type:valid.type,active_version:'YES',source_document_id:sourceId,evidence_block:d.evidence_block,document_type:d.document_type,updated_at:now_(),request_key:BRIDGE_REQUEST_KEY,redaction_verified:kind==='REDACTED'?'NO':'',translation_verified:kind==='EN_SUBTITLE'?'NO':''});previous.filter(x=>x.id!==id&&x.active_version==='YES').forEach(x=>patch_('06_DOCUMENT_REGISTER',x.id,{active_version:'NO',superseded_by:id}));audit_('PROCESSED_COPY_ADDED',d.case_id,id,'',kind,u.email);return {id};
 });}
function registerExternalAiOutput(id,validationReport){const u=requireCapability_('AI_USE'),external=document_(id,u);if(external.kind!=='AI_OUTPUT'||!['PENDING_REVIEW','UPLOADED'].includes(external.status)||external.active_version==='NO'||!external.source_document_id||!external.prompt_run_id)fail_('INVALID_INPUT','Pending linked AI output required');const kind={PRICE_REDACTION:'REDACTED',ENGLISH_SUBTITLE:'EN_SUBTITLE'}[external.ai_output_type];if(!kind)fail_('INVALID_INPUT','Unknown AI output type');const source=document_(external.source_document_id,u);if(source.case_id!==external.case_id)fail_('PERMISSION_DENIED','Output and source belong to different orders');const f=DriveApp.getFileById(external.file_id);if(f.getSize()>=MAX_FILE_BYTES_)fail_('OUTPUT_SIZE_BLOCKED','Existing output must be less than 3 MB');const blob=f.getBlob(),bytes=blob.getBytes(),hash=bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,bytes));if(external.sha256&&external.sha256!==hash)fail_('VERIFICATION_REQUIRED','External file checksum differs from registered bytes');if(blob.getContentType()!=='application/pdf')fail_('INVALID_FILE','External output must be a PDF');const registered=uploadProcessed(source.id,kind,{name:external.name||'external.pdf',type:'application/pdf',data:Utilities.base64Encode(bytes),prompt_run_id:external.prompt_run_id,validation_report:validationReport});auditOnce_('EXTERNAL_AI_OUTPUT_REGISTERED',external.case_id,id,id,registered.id,u);return {id:registered.id,source_ai_output_id:id,sha256:hash};}
function verifyProcessed(id,input){const u=requireCapability_('EVIDENCE_REVIEW');return lock_(()=>{const d=document_(id,u),kind=d.kind==='AI_OUTPUT'?{PRICE_REDACTION:'REDACTED',ENGLISH_SUBTITLE:'EN_SUBTITLE'}[d.ai_output_type]:d.kind;if(!['REDACTED','EN_SUBTITLE'].includes(kind)||d.active_version!=='YES')fail_('INVALID_INPUT','Processed active version required');if(d.kind==='AI_OUTPUT'&&d.status!=='PENDING_REVIEW')fail_('VERSION_CONFLICT','Pending AI output required');if(input.verified!==true||!text_(input.notes||'',2000))fail_('INVALID_INPUT','Human verification and notes required');const source=document_(d.source_document_id,u);if(kind==='REDACTED'&&!['EVIDENCE','SO'].includes(source.kind)||kind==='EN_SUBTITLE'&&!['EVIDENCE','SO','REDACTED'].includes(source.kind)||source.status!=='APPROVED'||source.active_version!=='YES'||source.kind==='REDACTED'&&source.redaction_verified!=='YES')fail_('VERSION_CONFLICT','Approved current source required');
 if(d.kind==='AI_OUTPUT'){const folder=aiOutputFolder_(order_(d.case_id,u),kind),files=folder.getFiles(),fileId=String(d.file_id||'');let inFolder=false;while(files.hasNext())if(files.next().getId()===fileId){inFolder=true;break;}if(!inFolder)fail_('VERIFICATION_REQUIRED','Output is not in the assigned Drive folder');}
 validateStoredDerivative_({...d,kind});const patch={status:'APPROVED',reviewed_by:u.email,reviewed_at:now_(),review_comment:input.notes,updated_at:now_()};if(d.kind==='AI_OUTPUT')patch.kind=kind;patch[kind==='REDACTED'?'redaction_verified':'translation_verified']='YES';patch_('06_DOCUMENT_REGISTER',id,patch);audit_('PROCESSED_VERIFIED',d.case_id,id,d.status,JSON.stringify(patch),u.email);return true;
 });}


function evidenceFolder_(t,m){if(!EVIDENCE_FOLDERS_.includes(t.evidence_block))fail_('EVIDENCE_BLOCK_REQUIRED','Map legacy evidence to one of the four blocks before uploading');if(!t.chain_node_id)return folder_(DriveApp.getFolderById(m.folder),t.evidence_block);const n=rows_('15_SUPPLY_CHAIN').find(n=>n.id===t.chain_node_id&&n.case_id===t.case_id&&n.material_id===m.id);if(!n||!n.folder)fail_('HUMAN_MAPPING_REQUIRED','Node folder mapping missing');return folder_(DriveApp.getFolderById(n.folder),EVIDENCE_FOLDER_NAMES_[t.evidence_block]);}
function removeDraftEvidence(id){const u=requireCapability_('EVIDENCE_UPLOAD');return withOperation_(()=>{const d=document_(id,u);if(d.kind!=='EVIDENCE'||d.active_version!=='YES'||!['DRAFT','UPLOADED'].includes(d.status)||d.uploaded_by!==u.email)fail_('PERMISSION_DENIED','Only uploader can remove active draft');const t=task_(d.task_id,u);if(t.document_id!==id||!['DRAFT','UPLOADED'].includes(t.status))fail_('VERSION_CONFLICT','Draft changed');patch_('06_DOCUMENT_REGISTER',id,{status:'SUPERSEDED',active_version:'NO',updated_at:now_()});patch_('04_EVIDENCE_TRACKER',t.id,{document_id:'',status:'MISSING',updated_at:now_()});auditOnce_('DRAFT_REMOVED',d.case_id,id,'UPLOADED','SUPERSEDED',u);return {id};});}
function repairExistingSOReviewTask(caseId){const u=requireCapability_('EVIDENCE_REVIEW');return withOperation_(()=>{const c=order_(caseId,u),d=document_(c.so_document_id,u);if(d.kind!=='SO'||d.case_id!==caseId)fail_('INVALID_INPUT','Registered Sales Order required');const tasks=rows_('04_EVIDENCE_TRACKER').filter(t=>t.case_id===caseId&&t.evidence==='Sales order');if(!tasks.length){const id=stable_('so-review:'+caseId);add_('04_EVIDENCE_TRACKER',{id,case_id:caseId,evidence:'Sales order',evidence_block:'01_Commercial_Shipping',department:'Marketing',owner:u.email,assigned_reviewer:u.email,required:'YES',status:'SUBMITTED',document_id:d.id,created_at:now_(),updated_at:now_()});}else tasks.forEach(t=>{if(t.status==='APPROVED')return;if(!canTask_(u,t))fail_('PERMISSION_DENIED','Review task outside scope');patch_('04_EVIDENCE_TRACKER',t.id,{document_id:d.id,status:['REJECTED','MORE_INFO_REQUIRED'].includes(t.status)?t.status:'SUBMITTED',updated_at:now_()});});if(['UPLOADED','DRAFT',''].includes(d.status||''))patch_('06_DOCUMENT_REGISTER',d.id,{status:'SUBMITTED',submitted_at:now_(),updated_at:now_()});auditOnce_('SO_REVIEW_TASK_REPAIRED',caseId,d.id,'','Human review required; no file duplicated',u);return {document_id:d.id};});}
function validateSubtitlePriceDecision_(source,v){if(source.kind==='REDACTED'){if(v.redaction_preserved!==true)fail_('REDACTION_NOT_VERIFIED','Confirm price masks remain intact in translated PDF');return;}if(v.price_check_performed!==true||typeof v.monetary_values_present!=='boolean')fail_('VERIFICATION_REQUIRED','Inspect the actual source for monetary values before translation');if(v.monetary_values_present){if(v.price_redaction_decision!=='DECLINED'||v.user_confirmed_unredacted_translation!==true||!text_(v.user_confirmation_excerpt||'',500))fail_('HUMAN_CONFIRMATION_REQUIRED','Record the user’s explicit decision to translate with prices visible');}else if(v.price_redaction_decision!=='NOT_REQUIRED')fail_('VERIFICATION_REQUIRED','No-price translation must record NOT_REQUIRED');}
function validateDerivedLineage_(source,kind,file){if(kind==='REDACTED'&&!['SO','EVIDENCE'].includes(source.kind)||kind==='EN_SUBTITLE'&&!['SO','EVIDENCE','REDACTED'].includes(source.kind)||!['REDACTED','EN_SUBTITLE'].includes(kind)||source.status!=='APPROVED'||source.active_version!=='YES')fail_('VERSION_CONFLICT','Approved current source required');if(kind==='EN_SUBTITLE'&&source.kind==='REDACTED'){if(source.redaction_verified!=='YES')fail_('VERIFICATION_REQUIRED','Verify redaction before translation');validateStoredDerivative_(source);}const r=rows_('18_AI_PROMPT_RUNS').find(r=>r.id===file.prompt_run_id);if(!r||r.case_id!==source.case_id||r.document_id!==source.id||r.function!==(kind==='REDACTED'?'PRICE_REDACTION':'ENGLISH_SUBTITLE'))fail_('INVALID_INPUT','Matching persisted prompt run required');const v=file.validation_report;if(!v||v.source_document_id!==source.id||!Number.isInteger(v.page_count)||v.page_count<1||v.original_page_count!==v.page_count||v.readability_checked!==true||v.traceability_preserved!==true)fail_('VERIFICATION_REQUIRED','Page mapping, readability and traceability validation required');if(kind==='REDACTED'&&['text_checked','annotations_checked','forms_checked','metadata_checked','pixels_sanitized','embedded_objects_removed'].some(k=>v[k]!==true))fail_('REDACTION_NOT_VERIFIED','Sanitization validation incomplete');if(kind==='EN_SUBTITLE')validateSubtitlePriceDecision_(source,v);}
function validateStoredDerivative_(d){const f=DriveApp.getFileById(d.file_id);if(f.getSize()>=MAX_FILE_BYTES_)fail_('OUTPUT_SIZE_BLOCKED','Derived PDF must be below 3 MB');let report;try{report=JSON.parse(d.validation_report);}catch(e){fail_('VERIFICATION_REQUIRED','Validation report missing');}const source=document_(d.source_document_id,user_());validateDerivedLineage_(source,d.kind,{prompt_run_id:d.prompt_run_id,validation_report:report});if(bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,f.getBlob().getBytes()))!==d.sha256)fail_('VERIFICATION_REQUIRED','Stored output checksum changed');}
