function csv_(rows){return rows.map(r=>r.map(v=>'"'+String(safe_(v??'')).replace(/"/g,'""')+'"').join(',')).join('\r\n');}
function exportPackage(caseId,input){const u=requireCapability_('EXPORT'),c=order_(caseId,u),history=input.include_history===true;if(history&&u.role!=='ADMIN')fail_('PERMISSION_DENIED','Only Admin can include history');
 return withOperation_(()=>{const candidates=rows_('06_DOCUMENT_REGISTER').filter(d=>d.case_id===caseId&&['SO','EVIDENCE','REDACTED','EN_SUBTITLE'].includes(d.kind)&&documentVisible_(d,u)),selected=input.document_ids||null;
 if(selected!==null&&(!Array.isArray(selected)||!selected.length||new Set(selected).size!==selected.length))fail_('INVALID_INPUT','Select unique document IDs');
 const docs=selected?selected.map(id=>{const d=candidates.find(x=>x.id===id);if(!d)fail_('FILE_NOT_FOUND','Selected document outside order');return d;}):candidates.filter(d=>history||d.status==='APPROVED'&&d.active_version==='YES');
 if(!docs.length)fail_('NO_EXPORTABLE_EVIDENCE','No approved active evidence');const all=rows_('06_DOCUMENT_REGISTER');
 docs.forEach(d=>{document_(d.id,u);if(!history&&(d.status!=='APPROVED'||d.active_version!=='YES'))fail_('VERSION_CONFLICT','Only approved active versions can be exported');
 if(d.kind==='REDACTED'&&d.redaction_verified!=='YES'||d.kind==='EN_SUBTITLE'&&d.translation_verified!=='YES')fail_('VERIFICATION_REQUIRED','Processed copy lacks human verification');if(['REDACTED','EN_SUBTITLE'].includes(d.kind))validateStoredDerivative_(d);
 if(d.source_document_id){const source=all.find(x=>x.id===d.source_document_id),expected=d.kind==='EN_SUBTITLE'?'REDACTED':d.kind==='REDACTED'?'ORIGINAL':'';if(!source||expected==='REDACTED'&&(source.kind!=='REDACTED'||source.redaction_verified!=='YES')||expected==='ORIGINAL'&&!['EVIDENCE','SO'].includes(source.kind)||!history&&(source.status!=='APPROVED'||source.active_version!=='YES'))fail_('VERSION_CONFLICT','Processed source is no longer current');if(expected==='REDACTED')validateStoredDerivative_(source);}});
 const id=stable_('export:'+caseId+':'+BRIDGE_REQUEST_KEY),old=rows_('19_EXPORT_LOG').find(x=>x.id===id);if(old)return {id,name:fileName_(c.so)+'_EUDR_PACKAGE.zip',download_id:'export:'+id,size_bytes:DriveApp.getFileById(old.file_id).getSize()};
 const materials=rows_('02_SO_ITEM_MATERIAL'),suppliers=rows_('14_SUPPLIERS'),nodes=rows_('15_SUPPLY_CHAIN'),manifest=[['File','Material','Supplier','Document Type','Version','Review Status','Reviewed By','Reviewed Date','Source File ID','Exported Date']],blobs=[];let total=0;const paths=new Set();
 docs.forEach(d=>{const f=DriveApp.getFileById(d.file_id);total+=f.getSize();if(total>23*1024*1024)fail_('EXPORT_TOO_LARGE','Current in-app ZIP limit is 23 MiB of source files; select a smaller package');const m=materials.find(m=>m.id===d.material_id),s=suppliers.find(s=>s.id===d.supplier_id),n=nodes.find(n=>n.id===d.chain_node_id),prefix=d.kind==='SO'?'Original/Order/00_SO':d.kind==='EVIDENCE'?'Original/'+fileName_(m?m.material:'Order')+'/'+fileName_(n?n.relationship||n.display_name:'KODA')+'/'+fileName_(d.evidence_block||'Evidence'):'Processed/'+d.kind,path=prefix+'/'+d.id+'_'+fileName_(d.name);if(paths.has(path))fail_('VERSION_CONFLICT','Duplicate export path');paths.add(path);blobs.push(f.getBlob().setName(path));manifest.push([path,m?m.material:'',s?s.name:'',d.document_type,d.version,d.status,d.reviewed_by,d.reviewed_at,d.file_id,now_()]);});
 const csv=csv_(manifest);blobs.push(Utilities.newBlob(csv,'text/csv','00_Index/Export_Manifest.csv'));blobs.push(Utilities.newBlob(csv,'text/csv','00_Index/Document_Index.csv'));blobs.push(Utilities.newBlob('Evidence package only. Internal document approvals do not constitute EUDR certification or an official due diligence statement.','text/plain','00_Index/Readme.txt'));
 const name=fileName_(c.so)+'_EUDR_PACKAGE.zip',zip=Utilities.zip(blobs,name);if(zip.getBytes().length>MAX_TRANSFER_)fail_('EXPORT_TOO_LARGE','ZIP exceeds 25 MiB transfer limit');const f=storeFile_(folder_(DriveApp.getFolderById(c.folder),'98_Export'),id,{bytes:zip.getBytes(),type:'application/zip'},name);
 add_('19_EXPORT_LOG',{id,case_id:caseId,actor:u.email,created_at:now_(),file_id:f.getId(),manifest_json:JSON.stringify(manifest),include_history:history?'YES':'NO',request_key:BRIDGE_REQUEST_KEY,document_ids:JSON.stringify(docs.map(d=>d.id))});audit_('EXPORT_CREATED',caseId,id,'',JSON.stringify(docs.map(d=>d.id)),u.email);return {id,name,download_id:'export:'+id,size_bytes:f.getSize()};
 });}
function getExport_(id,u){const ex=rows_('19_EXPORT_LOG').find(x=>x.id===id);if(!ex)fail_('FILE_NOT_FOUND','Export missing');order_(ex.case_id,u);if(u.role==='SUPPLIER_USER'||ex.include_history==='YES'&&u.role!=='ADMIN')fail_('PERMISSION_DENIED','Export access denied');authorizeExport_(ex,u);const f=DriveApp.getFileById(ex.file_id);if(f.getSize()>MAX_TRANSFER_)fail_('EXPORT_TOO_LARGE','ZIP exceeds limit');return {name:f.getName(),type:'application/zip',data:f.getSize()<=MAX_FILE_BYTES_?Utilities.base64Encode(f.getBlob().getBytes()):null,download_chunked:f.getSize()>MAX_FILE_BYTES_,size:f.getSize()};}


function authorizeExport_(ex,u){if(!hasCapability_(u,'EXPORT'))fail_('PERMISSION_DENIED','Export capability required');const ids=jsonList_(ex.document_ids);if(!ids.length)fail_('VERIFICATION_REQUIRED','Legacy export must be regenerated after access review');ids.forEach(id=>{const d=document_(id,u);if(d.case_id!==ex.case_id)fail_('PERMISSION_DENIED','Export lineage mismatch');if(ex.include_history!=='YES'&&(d.active_version!=='YES'||d.status!=='APPROVED'))fail_('VERSION_CONFLICT','Export contains superseded evidence; regenerate');if(['REDACTED','EN_SUBTITLE'].includes(d.kind)){if(d.kind==='REDACTED'&&d.redaction_verified!=='YES'||d.kind==='EN_SUBTITLE'&&d.translation_verified!=='YES')fail_('VERIFICATION_REQUIRED','Processed copy lacks human verification');validateStoredDerivative_(d);}});}

