function text_(v,max){if(typeof v!=='string')fail_('INVALID_INPUT','Text field required');if(v.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(v))fail_('INVALID_INPUT','Invalid text length/content');return v.trim();}
function stable_(s){return bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s)).slice(0,32);}
function isoDate_(d){if(typeof d!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d+'T12:00:00Z'))||new Date(d+'T12:00:00Z').toISOString().slice(0,10)!==d)fail_('INVALID_INPUT','Invalid calendar date');return d;}
function folder_(parent,name){const it=parent.getFoldersByName(name);if(it.hasNext()){const f=it.next();if(it.hasNext())fail_('VERSION_CONFLICT','Duplicate folder requires manual resolution');return f;}return parent.createFolder(name);}
function folderCandidates_(root,so){const it=root.getFolders(),found=[];while(it.hasNext()){const f=it.next(),name=f.getName();if(name===so||['(', ' ', '_', '-'].some(separator=>name.startsWith(so+separator)))found.push({id:f.getId(),name,url:f.getUrl()});}return found;}
function findOrderFolders(so){requireManager_();so=text_(so,100);if(!so||/[\\/]/.test(so))fail_('INVALID_INPUT','Order No. required');const rootId=PropertiesService.getScriptProperties().getProperty('ROOT_ID')||config_('DRIVE_ROOT_FOLDER_ID');return folderCandidates_(DriveApp.getFolderById(rootId),so);}
function fileName_(s){return text_(s,240).replace(/[\\/<>:"|?*\u0000-\u001f]/g,'_').replace(/^\.+/,'_')||'document';}
function notify_(email,caseId,objectId,message){if(!email)return;const id=stable_([BRIDGE_REQUEST_KEY,objectId,email,message].join(':'));if(!rows_('20_NOTIFICATIONS').some(x=>x.id===id))add_('20_NOTIFICATIONS',{id,email,case_id:caseId,object_id:objectId,message,read:'NO',created_at:now_()});}
function markNotification(id){const u=user_();return lock_(()=>{const n=rows_('20_NOTIFICATIONS').find(n=>n.id===id&&n.email===u.email);if(!n)fail_('PERMISSION_DENIED','Notification outside scope');patch_('20_NOTIFICATIONS',id,{read:'YES'});return true;});}
function withOperation_(fn){return lock_(()=>{
 const key=BRIDGE_REQUEST_KEY;if(!/^[a-zA-Z0-9_-]{16,80}$/.test(key||''))fail_('INVALID_INPUT','Idempotency key required');
 const id=stable_(BRIDGE_ACTOR+':'+BRIDGE_ACTION+':'+key),fingerprint=stable_(JSON.stringify(BRIDGE_ARGS)),old=rows_('21_OPERATIONS').find(r=>r.id===id);
 if(old&&old.fingerprint!==fingerprint)fail_('VERSION_CONFLICT','Idempotency key reused with different content');
 if(old&&old.status==='DONE')return JSON.parse(old.result_json);
 if(!old)add_('21_OPERATIONS',{id,actor:BRIDGE_ACTOR,action:BRIDGE_ACTION,fingerprint,status:'RUNNING',updated_at:now_()});
 try{const result=fn();patch_('21_OPERATIONS',id,{status:'DONE',result_json:JSON.stringify(result===undefined?null:result),updated_at:now_()});return result;}
 catch(e){patch_('21_OPERATIONS',id,{status:'RETRY_REQUIRED',updated_at:now_()});throw e;}
 });}
const BLOCKS_={
 'Sales order':'01_Commercial_Shipping',COO:'01_Commercial_Shipping',INV:'01_Commercial_Shipping',PL:'01_Commercial_Shipping',BL:'01_Commercial_Shipping',
 'Supplier FSC license':'02_FSC_Certification','FSC Cert':'02_FSC_Certification','Transport invoice':'03_Transport','GEO location':'04_Geolocation'
};
function createCase(input){return createOrder(input);}

function productInput_(p){if(!p||!text_(p.product_name||'',300))fail_('INVALID_INPUT','Product name required');const quantity=p.quantity===undefined||p.quantity===''?'':Number(p.quantity);if(quantity!==''&&(!Number.isFinite(quantity)||quantity<=0))fail_('INVALID_INPUT','Positive product quantity required');return {product_name:text_(p.product_name,300),sku:text_(p.sku||'',100),quantity,quantity_uom:text_(p.quantity_uom||'',40)};}
function createOrder(input){const u=requireCapability_('ORDER_EDIT');return withOperation_(()=>{
 const so=text_(input.so,100),customer=text_(input.customer||'',200),po=text_(input.po||'',200);if(!so||/[\\/]/.test(so))fail_('INVALID_INPUT','Valid Order No. required');if(input.due)isoDate_(input.due);
 if(!Array.isArray(input.products)||!input.products.length||input.products.length>100)fail_('INVALID_INPUT','Provide 1–100 products');const products=input.products.map(productInput_),valid=validateFile_(input.file);if(valid.type!=='application/pdf')fail_('INVALID_FILE','Sales Order must be PDF');
 const id=stable_('order:'+u.email+':'+BRIDGE_REQUEST_KEY),existing=rows_('01_SO_MASTER').find(c=>c.id===id);
 if(rows_('01_SO_MASTER').some(c=>c.id!==id&&String(c.so).trim().toLowerCase()===so.toLowerCase()))fail_('DUPLICATE_ORDER','Order No. already exists');
 const root=DriveApp.getFolderById(PropertiesService.getScriptProperties().getProperty('ROOT_ID')),candidates=existing?[]:folderCandidates_(root,so),selected=candidates.find(f=>f.id===input.existing_folder_id);
 if(input.existing_folder_id&&!selected&&!existing)fail_('HUMAN_MAPPING_REQUIRED','Select a verified existing folder');
 const canonical=so+' ['+id+']';if(candidates.some(f=>f.name!==canonical)&&!selected&&!existing)fail_('HUMAN_MAPPING_REQUIRED','Review existing folder candidates');
 const folder=existing?DriveApp.getFolderById(existing.folder):selected?DriveApp.getFolderById(selected.id):folder_(root,canonical),docId=stable_('SO:'+id);
 if(!existing)add_('01_SO_MASTER',{id,so,customer,po,due:input.due||'',owner:u.email,folder:folder.getId(),status:'NOT_STARTED',creation_state:'CREATING',created_at:now_(),updated_at:now_(),product:products[0].product_name,so_document_id:docId,request_key:BRIDGE_REQUEST_KEY});
 const file=storeFile_(folder_(folder,'00_SO'),docId,valid,fileName_(so)+'_SO.pdf');
 if(!rows_('06_DOCUMENT_REGISTER').some(d=>d.id===docId))add_('06_DOCUMENT_REGISTER',{id:docId,case_id:id,kind:'SO',document_type:'Sales order',name:file.getName(),file_id:file.getId(),version:1,status:'SUBMITTED',uploaded_by:u.email,created_at:now_(),submitted_at:now_(),mime_type:valid.type,active_version:'YES',file_size_bytes:valid.bytes.length,sha256:bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,valid.bytes)),request_key:BRIDGE_REQUEST_KEY});
 products.forEach((p,i)=>{const pid=stable_(id+':product:'+i);if(!rows_('24_SO_PRODUCTS').some(x=>x.id===pid))add_('24_SO_PRODUCTS',{...p,id:pid,case_id:id,sequence:i+1,active:'YES',created_at:now_(),created_by:u.email,updated_at:now_(),updated_by:u.email});});
 const tid=stable_('so-review:'+id);if(!rows_('04_EVIDENCE_TRACKER').some(t=>t.id===tid))add_('04_EVIDENCE_TRACKER',{id:tid,case_id:id,evidence:'Sales order',evidence_block:'01_Commercial_Shipping',department:'Marketing',owner:u.email,assigned_reviewer:u.email,required:'YES',status:'SUBMITTED',document_id:docId,created_at:now_(),updated_at:now_()});
 patch_('01_SO_MASTER',id,{creation_state:'COMPLETE',updated_at:now_()});auditOnce_('ORDER_CREATED',id,id,'',JSON.stringify({so,products:products.length}),u);
 return {id,products:rows_('24_SO_PRODUCTS').filter(p=>p.case_id===id).map(p=>({id:p.id,sequence:p.sequence}))};
 });}
function auditOnce_(action,caseId,id,before,after,u){const marker=stable_(u.email+':'+BRIDGE_ACTION+':'+BRIDGE_REQUEST_KEY+':'+action+':'+id);if(rows_('08_ACTIVITY_LOG').some(a=>a.id===marker))return;add_('08_ACTIVITY_LOG',{id:marker,timestamp:now_(),actor:u.email,role:u.role,action,case_id:caseId,entity_id:id,previous:before,next:after});}
function updateOrder(id,input){const u=requireCapability_('ORDER_EDIT');return withOperation_(()=>{const c=order_(id,u);if(input.expected_updated_at!==c.updated_at)fail_('VERSION_CONFLICT','Order changed; refresh');const value={updated_at:now_()};for(const k of ['so','customer','po','due'])if(input[k]!==undefined)value[k]=text_(input[k],k==='so'?100:200);if(value.so!==undefined&&(!value.so||/[\\/]/.test(value.so)||rows_('01_SO_MASTER').some(x=>x.id!==id&&String(x.so).toLowerCase()===value.so.toLowerCase())))fail_('DUPLICATE_ORDER','Invalid or duplicate Order No.');if(value.due)isoDate_(value.due);patch_('01_SO_MASTER',id,value);auditOnce_('ORDER_UPDATED',id,id,JSON.stringify(c),JSON.stringify(value),u);return {id};});}
function listOrderProducts(id){const u=user_();order_(id,u);if(u.role==='SUPPLIER_USER')return [];return rows_('24_SO_PRODUCTS').filter(p=>p.case_id===id);}
function saveOrderProduct(caseId,input){const u=requireCapability_('ORDER_EDIT');return withOperation_(()=>{order_(caseId,u);const products=rows_('24_SO_PRODUCTS').filter(p=>p.case_id===caseId),old=input.id?products.find(p=>p.id===input.id):null;if(input.id&&!old)fail_('INVALID_INPUT','Product outside order');const id=old?old.id:stable_('product:'+caseId+':'+BRIDGE_REQUEST_KEY);if(old&&input.expected_updated_at!==old.updated_at)fail_('VERSION_CONFLICT','Product changed; refresh');const value={...productInput_(input),updated_at:now_(),updated_by:u.email};if(old)patch_('24_SO_PRODUCTS',id,value);else if(!products.some(p=>p.id===id))add_('24_SO_PRODUCTS',{...value,id,case_id:caseId,sequence:products.length+1,active:'YES',created_at:now_(),created_by:u.email});auditOnce_('PRODUCT_SAVED',caseId,id,JSON.stringify(old||{}),JSON.stringify(value),u);return {id};});}
function removeOrderProduct(id){const u=requireCapability_('ORDER_EDIT');return withOperation_(()=>{const p=rows_('24_SO_PRODUCTS').find(p=>p.id===id);if(!p)fail_('INVALID_INPUT','Product missing');order_(p.case_id,u);if(rows_('24_SO_PRODUCTS').filter(x=>x.case_id===p.case_id&&x.active==='YES').length<=1)fail_('INVALID_INPUT','At least one active product required');if(rows_('02_SO_ITEM_MATERIAL').some(m=>jsonList_(m.product_ids).includes(id)))fail_('VERSION_CONFLICT','Product is linked to materials');patch_('24_SO_PRODUCTS',id,{active:'NO',updated_at:now_(),updated_by:u.email});auditOnce_('PRODUCT_REMOVED',p.case_id,id,'YES','NO',u);return {id};});}
function uploadProductImage(id,file){const u=requireCapability_('ORDER_EDIT');return withOperation_(()=>{const p=rows_('24_SO_PRODUCTS').find(p=>p.id===id);if(!p)fail_('INVALID_INPUT','Product missing');const c=order_(p.case_id,u),valid=validateFile_(file);if(!['image/png','image/jpeg','image/webp'].includes(valid.type))fail_('INVALID_FILE','PNG/JPG/WebP required');const did=stable_('product-image:'+id+':'+BRIDGE_REQUEST_KEY),old=rows_('06_DOCUMENT_REGISTER').find(d=>d.id===did);if(!old&&String(file.expected_document_id||'')!==String(p.image_document_id||''))fail_('VERSION_CONFLICT','Image changed; refresh');const f=storeFile_(folder_(DriveApp.getFolderById(c.folder),'00_Product_Images'),did,valid,did+'.'+({'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[valid.type]));if(!old)add_('06_DOCUMENT_REGISTER',{id:did,case_id:c.id,product_id:id,kind:'PRODUCT_IMAGE',name:valid.name,file_id:f.getId(),version:rows_('06_DOCUMENT_REGISTER').filter(d=>d.product_id===id).length+1,status:'UPLOADED',uploaded_by:u.email,created_at:now_(),mime_type:valid.type,active_version:'YES',file_size_bytes:valid.bytes.length,sha256:bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,valid.bytes))});if(p.image_document_id&&p.image_document_id!==did)patch_('06_DOCUMENT_REGISTER',p.image_document_id,{active_version:'NO',status:'SUPERSEDED',superseded_by:did});patch_('24_SO_PRODUCTS',id,{image_document_id:did,updated_at:now_(),updated_by:u.email});auditOnce_('PRODUCT_IMAGE_REPLACED',c.id,id,p.image_document_id||'',did,u);return {id:did};});}
function jsonList_(s){try{const x=JSON.parse(s||'[]');return Array.isArray(x)?x:[];}catch(e){return [];}}
function parseMaterials_(caseId,input){const u=requireCapability_('MATERIAL_EDIT'),c=order_(caseId,u);let obj;try{obj=typeof input==='string'?JSON.parse(input):input;}catch(e){fail_('INVALID_JSON','JSON cannot be parsed');}
 if(!obj||obj.order_no!==c.so||!Array.isArray(obj.materials)||!obj.materials.length||obj.materials.length>100)fail_('INVALID_INPUT','Order No. must match; provide 1–100 materials');
 const seen=new Set(),materials=obj.materials.map(m=>{const name=text_(m.material_name_normalized,150),original=text_(m.material_name_original,150),category=text_(m.material_category,50),reference=text_(m.source_reference,500);if(!name||!original||!reference||!['SOLID_WOOD','VENEER','MDF','PLYWOOD','OTHER_WOOD'].includes(category))fail_('INVALID_INPUT','Material name, category and source reference required');
 const k=name.toLowerCase();if(seen.has(k))fail_('DUPLICATE_MATERIAL','Duplicate material in imported result');seen.add(k);
 if(m.scientific_name!==null&&typeof m.scientific_name!=='string')fail_('INVALID_INPUT','Scientific name must be text or null');
 return {material:name,original,category,scientific_name:m.scientific_name?text_(m.scientific_name,200):'',source_reference:reference};});
 return {order_no:c.so,product:text_(obj.product||'',300),materials};
}
function previewMaterials(caseId,json){const result=parseMaterials_(caseId,json);return {...result,preview_hash:stable_(JSON.stringify(result))};}
function confirmMaterials(caseId,json,confirmation){const u=requireCapability_('MATERIAL_EDIT'),c=order_(caseId,u),preview=parseMaterials_(caseId,json);if(!confirmation||confirmation.confirmed!==true||confirmation.preview_hash!==stable_(JSON.stringify(preview)))fail_('VERSION_CONFLICT','Confirm the exact preview first');
 return withOperation_(()=>{const existing=rows_('02_SO_ITEM_MATERIAL').filter(m=>m.case_id===caseId),root=DriveApp.getFolderById(c.folder),ids=[];
 preview.materials.forEach((m,i)=>{const id=stable_(caseId+':material:'+m.material.toLowerCase()),old=existing.find(x=>x.id===id);if(old&&old.request_key!==BRIDGE_REQUEST_KEY)fail_('DUPLICATE_MATERIAL','Material already exists');
 const f=old?DriveApp.getFolderById(old.folder):folder_(root,fileName_(m.material)+' ['+id+']');Object.values(BLOCKS_).concat('05_Upstream_Traceability').filter((n,i,a)=>a.indexOf(n)===i).forEach(n=>folder_(f,n));
 if(!old)add_('02_SO_ITEM_MATERIAL',{id,case_id:caseId,material:m.material,category:m.category,material_original:m.original,common_species:'',commodity:'wood',scope_status:'NOT_PROVIDED',scientific_name:m.scientific_name,source_reference:m.source_reference,tier:'DIRECT',folder:f.getId(),source_system:'MP_IMPORT',source_key:id,confirmed_by:u.email,confirmed_at:now_(),request_key:BRIDGE_REQUEST_KEY});
 const rules=currentRequirements_().filter(r=>r.enabled==='YES'&&r.evidence!=='Sales order'&&(r.material==='*'||String(r.material).toLowerCase()===m.material.toLowerCase())&&(r.tier==='DIRECT'||r.tier==='*'));
 rules.forEach(r=>{const tid=stable_(id+':'+r.id);if(!rows_('04_EVIDENCE_TRACKER').some(t=>t.id===tid))add_('04_EVIDENCE_TRACKER',{id:tid,case_id:caseId,material_id:id,evidence:r.evidence,department:r.department,owner:'',due:c.due,status:'MISSING',evidence_block:BLOCKS_[r.evidence]||'05_Upstream_Traceability',required:'YES',priority:'NORMAL',created_at:now_(),updated_at:now_()});});ids.push(id);
 });
 patch_('01_SO_MASTER',caseId,{status:'COLLECTING_EVIDENCE',product:preview.product||c.product,updated_at:now_()});audit_('MATERIALS_CONFIRMED',caseId,'','',JSON.stringify(ids),u.email);return {ids};
 });}

function chainInput_(caseId,input,id){
 const m=rows_('02_SO_ITEM_MATERIAL').find(m=>m.id===input.material_id&&m.case_id===caseId);if(!m)fail_('INVALID_INPUT','Material outside order');
 if(!['SUPPLIER','PROCESSOR','TRADER','PRODUCER','FOREST_OWNER','LOG_SUPPLIER','PLOT'].includes(input.node_type))fail_('INVALID_INPUT','Invalid node type');
 const supplier=input.supplier_id?rows_('14_SUPPLIERS').find(s=>s.id===input.supplier_id&&s.active==='YES'):null;
 if(input.supplier_id&&!supplier||!supplier&&!['PRODUCER','FOREST_OWNER','PLOT'].includes(input.node_type))fail_('INVALID_INPUT','Select an active supplier');
 const name=supplier?supplier.name:text_(input.display_name||input.plot_id||'',200);if(!name)fail_('INVALID_INPUT','Producer or plot name required');
 const nodes=rows_('15_SUPPLY_CHAIN').filter(n=>n.case_id===caseId&&n.material_id===m.id),parent=input.parent_id?nodes.find(n=>n.id===input.parent_id):null;
 if(input.parent_id&&!parent)fail_('INVALID_INPUT','Parent outside material');
 const visited=new Set([id]);let cursor=parent,tier=1;while(cursor){if(visited.has(cursor.id))fail_('CHAIN_CYCLE','Cycle or self-parent');visited.add(cursor.id);tier++;cursor=nodes.find(n=>n.id===cursor.parent_id);}
 if(parent&&parent.terminal==='YES'&&input.node_type!=='PLOT')fail_('INVALID_INPUT','Unset terminal flag before adding an upstream supplier');
 const terminal=input.terminal==='YES';if(terminal&&(!['PRODUCER','FOREST_OWNER','PLOT'].includes(input.node_type)||nodes.some(n=>n.parent_id===id&&n.node_type!=='PLOT')))fail_('INVALID_INPUT','Terminal branch must represent production origin');
 if(input.node_type==='PLOT'&&!input.plot_id)fail_('INVALID_INPUT','Plot ID required');
 if(input.source_document_id){const d=document_(input.source_document_id,user_());if(d.case_id!==caseId||d.material_id!==m.id)fail_('INVALID_INPUT','Source outside material');}
 return {m,parent,value:{case_id:caseId,material_id:m.id,supplier_id:input.supplier_id||'',parent_id:input.parent_id||'',node_type:input.node_type,display_name:name,plot_id:text_(input.plot_id||'',150),source_document_id:input.source_document_id||'',tier,relationship:(parent?(parent.display_name||'Upstream supplier'):'KODA')+' - '+name,terminal:terminal?'YES':'NO',status:'UPSTREAM_INCOMPLETE'}};
}
function addChainNode(caseId,input){const u=requireCapability_('CHAIN_EDIT');return withOperation_(()=>{order_(caseId,u);const id=stable_('chain:'+caseId+':'+BRIDGE_REQUEST_KEY),old=rows_('15_SUPPLY_CHAIN').find(n=>n.id===id);if(old){syncNodeRequirements_(id,u);return {id};}const {m,value}=chainInput_(caseId,input,id),f=folder_(DriveApp.getFolderById(m.folder),fileName_(value.relationship)+' ['+id+']');add_('15_SUPPLY_CHAIN',{...value,id,folder:f.getId(),created_at:now_(),created_by:u.email,updated_at:now_(),updated_by:u.email});syncNodeRequirements_(id,u);auditOnce_('CHAIN_NODE_ADDED',caseId,id,'',JSON.stringify(value),u);return {id};});}
function updateChainNode(id,input){const u=requireCapability_('CHAIN_EDIT');return withOperation_(()=>{const old=rows_('15_SUPPLY_CHAIN').find(n=>n.id===id);if(!old)fail_('INVALID_INPUT','Node missing');order_(old.case_id,u);const merged={...old,...input,case_id:old.case_id,material_id:old.material_id},checked=chainInput_(old.case_id,merged,id);patch_('15_SUPPLY_CHAIN',id,{...checked.value,updated_at:now_(),updated_by:u.email});const nodes=rows_('15_SUPPLY_CHAIN').filter(n=>n.case_id===old.case_id&&n.material_id===old.material_id);nodes.forEach(n=>{const seen=new Set();let p=n,depth=0;while(p){if(seen.has(p.id))fail_('CHAIN_CYCLE','Invalid stored graph');seen.add(p.id);depth++;p=nodes.find(x=>x.id===p.parent_id);}if(n.tier!==depth)patch_('15_SUPPLY_CHAIN',n.id,{tier:depth});});auditOnce_('CHAIN_NODE_UPDATED',old.case_id,id,JSON.stringify(old),JSON.stringify(checked.value),u);return {id};});}
function syncNodeRequirements_(nodeId,u){const node=rows_('15_SUPPLY_CHAIN').find(n=>n.id===nodeId),m=rows_('02_SO_ITEM_MATERIAL').find(m=>m.id===node.material_id),rules=currentRequirements_().filter(r=>r.enabled==='YES'&&(!r.effective_date||r.effective_date<=now_().slice(0,10))&&(r.material==='*'||r.material===m.material||r.material===m.category)&&(!r.node_type||r.node_type==='*'||r.node_type===node.node_type)&&(r.tier==='*'||r.tier==='DIRECT'&&Number(node.tier)===1||String(r.tier)===String(node.tier))&&r.evidence!=='Sales order');
 rules.forEach(r=>{const id=stable_('task:'+nodeId+':'+r.id);if(!rows_('04_EVIDENCE_TRACKER').some(t=>t.id===id))add_('04_EVIDENCE_TRACKER',{id,case_id:m.case_id,material_id:m.id,chain_node_id:nodeId,supplier_id:node.supplier_id,evidence:r.evidence,department:r.department,owner:u.email,required:r.required||'YES',requirement_id:r.id,rule_version:r.rule_version||'LEGACY',evidence_block:BLOCKS_[r.evidence]||'05_Upstream_Traceability',status:'MISSING',created_at:now_(),updated_at:now_()});});
}
function updateEvidenceRequirement(input){const u=requireCapability_('POLICY_EDIT');return withOperation_(()=>{const old=input.id?rows_('03_EVIDENCE_REQUIREMENT').find(r=>r.id===input.id):null;if(input.id&&!old)fail_('INVALID_INPUT','Requirement missing');const value={material:text_(input.material||'*',150),evidence:text_(input.evidence||'',200),department:text_(input.department||'Purchasing',100),tier:text_(input.tier||'*',30),node_type:text_(input.node_type||'*',50),enabled:input.enabled||'YES',required:input.required||'YES',rule_version:text_(input.rule_version||'',100),effective_date:isoDate_(input.effective_date),updated_at:now_(),updated_by:u.email};if(!['*','DIRECT'].includes(value.tier)&&! /^[1-9][0-9]*$/.test(value.tier)||!['*','SUPPLIER','PROCESSOR','TRADER','PRODUCER','FOREST_OWNER','LOG_SUPPLIER','PLOT'].includes(value.node_type))fail_('INVALID_INPUT','Invalid tier or node type');if(!value.evidence||!value.rule_version||!['YES','NO'].includes(value.enabled)||!['YES','NO'].includes(value.required))fail_('INVALID_INPUT','Evidence, version and flags required');const id=stable_('requirement:'+u.email+':'+BRIDGE_REQUEST_KEY);if(!rows_('03_EVIDENCE_REQUIREMENT').some(r=>r.id===id))add_('03_EVIDENCE_REQUIREMENT',{...value,id,policy_id:old?(old.policy_id||old.id):id});auditOnce_('EVIDENCE_POLICY_VERSIONED','',id,JSON.stringify(old||{}),JSON.stringify(value),u);return {id,note:'Existing tasks retain their recorded requirement version'};});}
function updateTask(id,change){const u=requireCapability_('EVIDENCE_REVIEW'),t=task_(id,u);if(change.status!==undefined)fail_('INVALID_INPUT','Use reviewDocument for status decisions');return lock_(()=>{
 const o={updated_at:now_()};if(change.owner==='')o.owner='';else if(change.owner!==undefined){const owner=rows_('05_OWNER_MASTER').find(x=>x.email===change.owner&&x.active==='YES');if(!owner)fail_('INVALID_INPUT','Owner not active');o.owner=owner.email;if(owner.role==='SUPPLIER_USER')o.supplier_id=owner.supplier_id;}
 if(change.supplier_id!==undefined){if(change.supplier_id&&!rows_('14_SUPPLIERS').some(s=>s.id===change.supplier_id&&s.active==='YES'))fail_('INVALID_INPUT','Supplier not active');o.supplier_id=change.supplier_id;}
 const finalSupplier=o.supplier_id===undefined?t.supplier_id:o.supplier_id,finalOwner=o.owner===undefined?t.owner:o.owner,owner=rows_('05_OWNER_MASTER').find(x=>x.email===finalOwner);if(owner&&owner.role==='SUPPLIER_USER'&&owner.supplier_id!==finalSupplier)fail_('INVALID_INPUT','Owner/supplier mismatch');
 if(change.assigned_reviewer!==undefined){if(change.assigned_reviewer&&!rows_('05_OWNER_MASTER').some(x=>x.email===change.assigned_reviewer&&x.active==='YES'&&hasCapability_(x,'EVIDENCE_REVIEW')))fail_('INVALID_INPUT','Active reviewer required');o.assigned_reviewer=change.assigned_reviewer;}
 if(change.due!==undefined)o.due=change.due?isoDate_(change.due):'';if(change.priority!==undefined){if(!['LOW','NORMAL','HIGH','URGENT'].includes(change.priority))fail_('INVALID_INPUT','Invalid priority');o.priority=change.priority;}
 patch_('04_EVIDENCE_TRACKER',id,o);notify_(o.owner||t.owner,t.case_id,id,'Evidence task assigned or updated');const sync=syncTaskCalendar_({...t,...o});audit_('TASK_ASSIGNED',t.case_id,id,JSON.stringify(t),JSON.stringify(o),u.email);return {saved:true,calendar:sync};
 });}


function createMaterial(caseId,input){const u=requireCapability_('MATERIAL_EDIT');return withOperation_(()=>{const c=order_(caseId,u),name=text_(input.material||'',150),category=text_(input.category||'',50);if(!name||!['SOLID_WOOD','VENEER','MDF','PLYWOOD','OTHER_WOOD'].includes(category))fail_('INVALID_INPUT','Material and category required');const products=input.product_ids||[];if(!Array.isArray(products)||products.some(id=>!rows_('24_SO_PRODUCTS').some(p=>p.id===id&&p.case_id===caseId&&p.active==='YES')))fail_('INVALID_INPUT','Product outside order');const id=stable_('material:'+caseId+':'+BRIDGE_REQUEST_KEY),old=rows_('02_SO_ITEM_MATERIAL').find(m=>m.id===id);if(old)return {id};const f=folder_(DriveApp.getFolderById(c.folder),fileName_(name)+' ['+id+']');add_('02_SO_ITEM_MATERIAL',{id,case_id:caseId,material:name,category,commodity:'wood',supplier_po:text_(input.supplier_po||'',200),scientific_name:'',product_ids:JSON.stringify([...new Set(products)]),folder:f.getId(),source_system:'MP_MANUAL',source_reference:text_(input.source_reference||'',500),request_key:BRIDGE_REQUEST_KEY,updated_at:now_(),updated_by:u.email});auditOnce_('MATERIAL_CREATED',caseId,id,'',name,u);return {id};});}
function updateMaterial(id,input){const u=requireCapability_('MATERIAL_EDIT');return withOperation_(()=>{const m=rows_('02_SO_ITEM_MATERIAL').find(m=>m.id===id);if(!m)fail_('INVALID_INPUT','Material missing');order_(m.case_id,u);const value={updated_at:now_(),updated_by:u.email};for(const k of ['material','supplier_po','source_reference'])if(input[k]!==undefined)value[k]=text_(input[k],k==='source_reference'?500:200);if(value.material==='')fail_('INVALID_INPUT','Material name required');if(input.product_ids!==undefined){if(!Array.isArray(input.product_ids)||input.product_ids.some(id=>!rows_('24_SO_PRODUCTS').some(p=>p.id===id&&p.case_id===m.case_id&&p.active==='YES')))fail_('INVALID_INPUT','Product outside order');value.product_ids=JSON.stringify([...new Set(input.product_ids)]);}patch_('02_SO_ITEM_MATERIAL',id,value);auditOnce_('MATERIAL_UPDATED',m.case_id,id,JSON.stringify(m),JSON.stringify(value),u);return {id};});}


function currentRequirements_(){const latest=new Map();rows_('03_EVIDENCE_REQUIREMENT').filter(r=>!r.effective_date||r.effective_date<=now_().slice(0,10)).forEach(r=>{const key=r.policy_id||r.id,old=latest.get(key);if(!old||String(r.effective_date||'')>String(old.effective_date||'')||r.effective_date===old.effective_date&&String(r.updated_at||'')>String(old.updated_at||''))latest.set(key,r);});return [...latest.values()];}
