const fs=require('fs'),vm=require('vm'),assert=require('assert');
const manifest=JSON.parse(fs.readFileSync(__dirname+'/appsscript.json','utf8'));
assert(manifest.oauthScopes.includes('https://www.googleapis.com/auth/calendar'));
const ctx={console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/Code.gs','utf8'),ctx);
let attached=0;
ctx.attachPreparedSheet=()=>{attached++;return {spreadsheet:'prepared-sheet'};};
assert.equal(ctx.setup().spreadsheet,'prepared-sheet');
assert.equal(attached,1);
assert.throws(()=>ctx.setup({}),/supply both Sheet and root Folder IDs/);
const schema=vm.runInContext('SCHEMA',ctx),prepared=vm.runInContext('PREPARED',ctx);
let props={DB_ID:'old-workbook'},updates=[],calendarAvailable=true;
ctx.PropertiesService={getScriptProperties:()=>({getProperty:key=>props[key]||'',setProperties:next=>{updates.push(next);Object.assign(props,next);}})};
ctx.SpreadsheetApp={openById:id=>{
 assert.equal(id,prepared.sheetId);
 return {getSheetByName:name=>schema[name]?{getRange:()=>({getValues:()=>[schema[name]]})}:null,getUrl:()=> 'prepared-url'};
}};
ctx.DriveApp={getFolderById:id=>{assert.equal(id,prepared.rootFolderId);return {getName:()=> 'EUDR',getUrl:()=> 'folder-url'};}};
ctx.CalendarApp={getCalendarById:id=>{assert.equal(id,prepared.calendarId);return calendarAvailable?{}:null;}};
ctx.Session={getEffectiveUser:()=>({getEmail:()=> 'owner@koda.test'})};
ctx.rows_=()=>[];ctx.add_=()=>{};ctx.audit_=()=>{};
assert.equal(ctx.diagnoseConnection().currentSheetId,'old-workbook');
assert.throws(()=>ctx.connectPreparedSheet_(false),/different Sheet/);
assert.equal(updates.length,0);
calendarAvailable=false;
assert.throws(()=>ctx.reconnectPreparedSheet(),/Calendar unavailable/);
assert.equal(updates.length,0);
calendarAvailable=true;
assert.equal(ctx.reconnectPreparedSheet().spreadsheet,'prepared-url');
assert.equal(props.DB_ID,prepared.sheetId);
assert.equal(props.PREVIOUS_DB_ID,'old-workbook');
assert.equal(updates.length,1);
let data,role,patches;
ctx.user_=()=>({email:'owner@koda.test',role});ctx.now_=()=> '2026-10-05';ctx.lock_=f=>f();ctx.audit_=()=>{};ctx.rows_=n=>data[n]||[];ctx.patch_=(n,id,o)=>{patches.push([n,id,o]);Object.assign(data[n].find(r=>r.id===id),o);};ctx.config_=()=> 'YES';
function reset(){role='MARKETING';patches=[];data={'04_EVIDENCE_TRACKER':[{id:'t',case_id:'c',owner:'owner@koda.test',status:'Missing'}],'01_SO_MASTER':[{id:'c'}],'06_DOCUMENT_REGISTER':[]};}
reset();assert.throws(()=>ctx.updateTask('t',{status:'Accepted'}),/Upload evidence/);
reset();role='CONTRIBUTOR';assert.throws(()=>ctx.updateTask('t',{status:'Accepted'}),/Marketing\/Admin/);
reset();assert.throws(()=>ctx.completeCase('c'),/All evidence/);
reset();data['04_EVIDENCE_TRACKER'][0].status='Received';assert.throws(()=>ctx.updateTask('t',{status:'Rework'}),/reason/);
reset();data['04_EVIDENCE_TRACKER'][0].status='Received';ctx.updateTask('t',{status:'Accepted'});assert.equal(data['04_EVIDENCE_TRACKER'][0].status,'Accepted');assert.throws(()=>ctx.completeCase('c'),/Register final/);
data['06_DOCUMENT_REGISTER'].push({id:'o',case_id:'c',kind:'OUTPUT',version:1});ctx.completeCase('c');assert.equal(data['01_SO_MASTER'][0].status,'Completed');assert.equal(data['06_DOCUMENT_REGISTER'][0].status,'Approved');
reset();role='CONTRIBUTOR';data['06_DOCUMENT_REGISTER'].push({id:'other',task_id:'other'});assert.throws(()=>ctx.getDocument('other'),/access denied/);
reset();role='CONTRIBUTOR';assert.throws(()=>ctx.uploadEvidence('other',{}),/access denied/);
reset();ctx.config_=()=> 'NO';assert.throws(()=>ctx.completeCase('c'),/confirm requirement/);
assert.equal(ctx.safe_('=IMPORTXML("x")'),"'=IMPORTXML(\"x\")");
reset();data['02_SO_ITEM_MATERIAL']=[{id:'m',material:'MDF',supplier:'Supplier'}];data['04_EVIDENCE_TRACKER'][0].material_id='m';data['04_EVIDENCE_TRACKER'][0].evidence='GEO location';data['04_EVIDENCE_TRACKER'][0].due='2026-10-09';data['01_SO_MASTER'][0].so='SO26-001';
let count=0,deleted=0,ev={getId:()=> 'event-1',setTitle(){},setAllDayDate(){},setDescription(){},deleteEvent(){deleted++}};
const cal={getEventById:id=>id==='event-1'?ev:null,createAllDayEvent(){count++;return ev}};
ctx.CalendarApp={getCalendarById:()=>cal};ctx.PropertiesService={getScriptProperties:()=>({getProperty:()=> 'calendar-id'})};
ctx.syncCalendar();ctx.syncCalendar();assert.equal(count,1);assert.equal(data['04_EVIDENCE_TRACKER'][0].calendar_event_id,'event-1');
data['04_EVIDENCE_TRACKER'][0].status='Accepted';ctx.syncCalendar();assert.equal(deleted,1);assert.equal(data['04_EVIDENCE_TRACKER'][0].calendar_event_id,'');
reset();data['01_SO_MASTER'][0].so='SO26-001';data['01_SO_MASTER'][0].customer='Customer A';data['02_SO_ITEM_MATERIAL']=[{id:'m',case_id:'c',sku:'SKU-1',material:'MDF',supplier:'Supplier A',tier:'DIRECT'}];data['04_EVIDENCE_TRACKER'][0].material_id='m';data['04_EVIDENCE_TRACKER'][0].evidence='GEO';data['06_DOCUMENT_REGISTER']=[{id:'d',case_id:'c',task_id:'t',kind:'EVIDENCE',name:'Supplier A GEO.pdf',status:'Received'}];
const prompt=ctx.getAiPrompt('c','English');assert.match(prompt.prompt,/SO26-001/);assert.match(prompt.prompt,/Supplier A GEO.pdf/);assert.match(prompt.prompt,/log supplier/);assert.match(prompt.prompt,/text layer/);
role='CONTRIBUTOR';data['04_EVIDENCE_TRACKER'][0].owner='someone-else@koda.test';assert.throws(()=>ctx.getAiPrompt('c','English'),/access denied/);
console.log('Workflow/security and Calendar idempotency checks passed (mocked Apps Script services).');
