// Durable 1 MiB chunks avoid Netlify's per-request body/response limits.
// Final assembly is capped at 25 MiB and requires live Apps Script resource testing.
const TRANSFER_CHUNK_=1024*1024,MAX_TRANSFER_=25*1024*1024;
function beginUpload(taskId,metadata){const u=requireCapability_('EVIDENCE_UPLOAD');const t=task_(taskId,u),size=Number(metadata.size);if(t.evidence==='Sales order'||!['MISSING','DRAFT','UPLOADED','REJECTED','MORE_INFO_REQUIRED'].includes(t.status))fail_('PERMISSION_DENIED','Upload not permitted in this task state');
 if(!Number.isSafeInteger(size)||size<1||size>MAX_TRANSFER_||! /^[a-f0-9]{64}$/.test(metadata.sha256||''))fail_('INVALID_FILE','Valid size and SHA-256 required; maximum 25 MiB');
 if(!['application/pdf','image/png','image/jpeg','application/json','application/geo+json'].includes(metadata.type))fail_('INVALID_FILE','Unsupported file type');
 let source=null;if(metadata.kind)fail_('INVALID_INPUT','Use derived output registration with validation report; maximum file size 3 MB');
 if(metadata.expected_document_id!==String(t.document_id||'')||!source&&t.status==='APPROVED')fail_('VERSION_CONFLICT','Refresh or request revision before uploading');
 return withOperation_(()=>{const id=stable_('upload:'+u.email+':'+BRIDGE_REQUEST_KEY),old=rows_('23_UPLOAD_SESSIONS').find(s=>s.id===id);if(old)return {id,chunk_size:TRANSFER_CHUNK_,chunk_count:Number(old.chunk_count)};
 const c=order_(t.case_id,u),f=folder_(folder_(DriveApp.getFolderById(c.folder),'99_Archive'),'UPLOAD_'+id),count=Math.ceil(size/TRANSFER_CHUNK_);add_('23_UPLOAD_SESSIONS',{id,actor:u.email,case_id:t.case_id,task_id:taskId,name:fileName_(metadata.name),mime_type:metadata.type,size,sha256:metadata.sha256,chunk_count:count,folder_id:f.getId(),expected_document_id:metadata.expected_document_id,status:'UPLOADING',created_at:now_(),request_key:BRIDGE_REQUEST_KEY,kind:metadata.kind||'EVIDENCE',source_document_id:metadata.source_document_id||''});return {id,chunk_size:TRANSFER_CHUNK_,chunk_count:count};});
}
function uploadSession_(id,u){const session=rows_('23_UPLOAD_SESSIONS').find(s=>s.id===id&&s.actor===u.email);if(!session)fail_('PERMISSION_DENIED','Upload session outside user scope');task_(session.task_id,u);return session;}
function uploadChunk(sessionId,index,data){const u=user_();requireWrite_(u);const s=uploadSession_(sessionId,u);if(!Number.isInteger(index)||index<0||index>=Number(s.chunk_count)||typeof data!=='string'||data.length>1400000||! /^[A-Za-z0-9+/]+={0,2}$/.test(data))fail_('INVALID_FILE','Invalid chunk');const bytes=Utilities.base64Decode(data),expected=index===Number(s.chunk_count)-1?Number(s.size)-index*TRANSFER_CHUNK_:TRANSFER_CHUNK_;if(bytes.length!==expected)fail_('INVALID_FILE','Chunk size mismatch');
 return lock_(()=>{const f=DriveApp.getFolderById(s.folder_id),name=String(index).padStart(4,'0')+'.bin',files=f.getFilesByName(name),hash=bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,bytes));
 if(files.hasNext()){const file=files.next();if(files.hasNext()||file.getDescription()!==hash)fail_('VERSION_CONFLICT','Chunk content differs from existing chunk');return {index};}
 if(s.status==='DONE')fail_('VERSION_CONFLICT','Upload session completed');const file=f.createFile(Utilities.newBlob(bytes,'application/octet-stream',name));file.setDescription(hash);return {index};});
}
function finishUpload(sessionId){const u=user_();requireWrite_(u);const s=uploadSession_(sessionId,u);if(s.status==='DONE')return {id:s.document_id};
 const bytes=[],folder=DriveApp.getFolderById(s.folder_id);for(let i=0;i<Number(s.chunk_count);i++){const it=folder.getFilesByName(String(i).padStart(4,'0')+'.bin');if(!it.hasNext())fail_('INCOMPLETE_UPLOAD','A chunk is missing');const f=it.next();if(it.hasNext())fail_('VERSION_CONFLICT','Duplicate upload chunk');const chunk=f.getBlob().getBytes();const hash=bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,chunk));if(hash!==f.getDescription())fail_('INVALID_FILE','Stored chunk integrity failed');for(let j=0;j<chunk.length;j++)bytes.push(chunk[j]);}
 if(bytes.length!==Number(s.size)||bridgeHex_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,bytes))!==s.sha256)fail_('INVALID_FILE','File checksum does not match');
 const key=BRIDGE_REQUEST_KEY,args=BRIDGE_ARGS;BRIDGE_REQUEST_KEY='finish_'+s.id;BRIDGE_ARGS=[sessionId,s.sha256];let result;
 try{const file={name:s.name,type:s.mime_type,data:Utilities.base64Encode(bytes),expected_document_id:s.expected_document_id};result=s.kind==='EVIDENCE'?uploadEvidence(s.task_id,file,MAX_TRANSFER_):uploadProcessed(s.source_document_id,s.kind,file,MAX_TRANSFER_);}finally{BRIDGE_REQUEST_KEY=key;BRIDGE_ARGS=args;}
 patch_('23_UPLOAD_SESSIONS',s.id,{status:'DONE',document_id:result.id});return result;
}
function downloadFile_(id,u){if(String(id).startsWith('export:')){const ex=rows_('19_EXPORT_LOG').find(x=>x.id===String(id).slice(7));if(!ex)fail_('FILE_NOT_FOUND','Export missing');order_(ex.case_id,u);if(u.role==='SUPPLIER_USER'||ex.include_history==='YES'&&u.role!=='ADMIN')fail_('PERMISSION_DENIED','Export access denied');authorizeExport_(ex,u);return DriveApp.getFileById(ex.file_id);}return DriveApp.getFileById(document_(id,u).file_id);}
function getDocumentChunk(id,index){const u=user_(),f=downloadFile_(id,u),size=f.getSize(),chunks=Math.ceil(size/TRANSFER_CHUNK_);if(!Number.isInteger(index)||index<0||index>=chunks||size>MAX_TRANSFER_)fail_('INVALID_INPUT','Invalid download chunk or size');
 const start=index*TRANSFER_CHUNK_,end=Math.min(size-1,start+TRANSFER_CHUNK_-1),url='https://www.googleapis.com/drive/v3/files/'+encodeURIComponent(f.getId())+'?alt=media';
 const response=UrlFetchApp.fetch(url,{headers:{Authorization:'Bearer '+ScriptApp.getOAuthToken(),Range:'bytes='+start+'-'+end},muteHttpExceptions:true});
 if(response.getResponseCode()!==206)fail_('DOWNLOAD_FAILED','Drive did not honor the bounded byte range');const blob=response.getBlob();if(blob.getBytes().length!==end-start+1)fail_('DOWNLOAD_FAILED','Chunk size mismatch');return {index,size,data:Utilities.base64Encode(blob.getBytes())};
}
