function bootstrap(){const u=user_(),tasks=rows_('04_EVIDENCE_TRACKER').filter(t=>canTask_(u,t)),orders=rows_('01_SO_MASTER').filter(c=>canOrder_(u,c)),supplier=u.role==='SUPPLIER_USER',ids=new Set(orders.map(c=>c.id)),materialIds=new Set(tasks.map(t=>t.material_id));
 const materials=rows_('02_SO_ITEM_MATERIAL').filter(m=>ids.has(m.case_id)&&(!supplier||materialIds.has(m.id)));
 const cases=orders.map(c=>{const own=tasks.filter(t=>t.case_id===c.id&&t.required!=='NO'),approved=own.filter(t=>t.status==='APPROVED').length,issues=supplier?[]:materials.filter(m=>m.case_id===c.id).flatMap(m=>materialIssues_(m));const expired=rows_('06_DOCUMENT_REGISTER').filter(d=>d.case_id===c.id&&d.active_version==='YES'&&d.expiry_date&&d.expiry_date<new Date().toISOString().slice(0,10));if(expired.length)issues.push('EXPIRED_CERTIFICATE');return {...c,folder:supplier?'':c.folder,so_document_id:supplier?'':c.so_document_id,product_image_id:supplier?'':c.product_image_id,readiness:own.length?Math.round(approved*100/own.length):0,total:own.length,accepted:approved,issues,status:c.status==='CLOSED'?'CLOSED':own.some(t=>['REJECTED','MORE_INFO_REQUIRED'].includes(t.status))?'ACTION_REQUIRED':own.length&&approved===own.length&&!issues.length?'READY_FOR_OPERATOR_REVIEW':own.some(t=>['UPLOADED','SUBMITTED','IN_REVIEW'].includes(t.status))?'IN_REVIEW':'COLLECTING_EVIDENCE'};});
 const docs=rows_('06_DOCUMENT_REGISTER').filter(d=>ids.has(d.case_id)&&(!supplier||tasks.some(t=>t.id===d.task_id)&&d.supplier_id===u.supplier_id)).map(d=>{const copy={...d};delete copy.file_id;delete copy.request_key;if(supplier){delete copy.review_comment;delete copy.uploaded_by;delete copy.reviewed_by;}return copy;});
 const chain=rows_('15_SUPPLY_CHAIN').filter(n=>ids.has(n.case_id)&&(!supplier||materialIds.has(n.material_id)&&n.supplier_id===u.supplier_id)),geo=rows_('17_GEO_LOCATIONS').filter(g=>ids.has(g.case_id)&&(!supplier||materialIds.has(g.material_id)&&g.supplier_id===u.supplier_id));
 const owners=u.role==='ADMIN'?rows_('05_OWNER_MASTER'):['MARKETING','EUDR_REVIEWER'].includes(u.role)?rows_('05_OWNER_MASTER').filter(x=>x.active==='YES').map(x=>({email:x.email,name:x.name,role:x.role,supplier_id:x.supplier_id})):[];
 return {user:u,cases,tasks,materials:materials.map(m=>({...m,folder:supplier?'':m.folder})),docs,owners,chain,geo,suppliers:rows_('14_SUPPLIERS').filter(s=>!supplier||s.id===u.supplier_id),notifications:rows_('20_NOTIFICATIONS').filter(n=>n.email===u.email&&ids.has(n.case_id)),audit:supplier?[]:rows_('08_ACTIVITY_LOG').filter(a=>u.role==='ADMIN'||ids.has(a.case_id)).slice(-250),countryRisk:supplier?[]:rows_('22_COUNTRY_RISK').filter(r=>r.rule_version===config_('COUNTRY_RISK_VERSION')),settings:u.role==='ADMIN'?rows_('09_CONFIG'):[],legal:supplier?null:legalState_(),rulesConfirmed:config_('RULES_CONFIRMED')==='YES'};
}
function completeCase(caseId,input){const u=requireRole_(['ADMIN','EUDR_REVIEWER']);order_(caseId,u);if(!input||input.confirmed!==true||!text_(input.comment||'',2000))fail_('HUMAN_CONFIRMATION_REQUIRED','Human closure confirmation and notes required');return lock_(()=>{
 const required=rows_('04_EVIDENCE_TRACKER').filter(t=>t.case_id===caseId&&t.required!=='NO'),materials=rows_('02_SO_ITEM_MATERIAL').filter(m=>m.case_id===caseId);
 if(config_('RULES_CONFIRMED')!=='YES'||!required.length||required.some(t=>t.status!=='APPROVED')||!materials.length||materials.some(m=>materialIssues_(m).length))fail_('EVIDENCE_INCOMPLETE','Resolve required evidence and traceability before closure');
 if(legalState_().reviewDue)fail_('LEGAL_REVIEW_DUE','Legal baseline review is due');
 if(rows_('06_DOCUMENT_REGISTER').some(d=>d.case_id===caseId&&d.active_version==='YES'&&d.expiry_date&&d.expiry_date<new Date().toISOString().slice(0,10)))fail_('EVIDENCE_INCOMPLETE','Resolve expired certificates before closure');
 if(!rows_('19_EXPORT_LOG').some(ex=>ex.case_id===caseId&&ex.include_history!=='YES'))fail_('EXPORT_REQUIRED','Create an approved evidence export first');
 patch_('01_SO_MASTER',caseId,{status:'CLOSED',updated_at:now_()});audit_('ORDER_CLOSED',caseId,caseId,'READY_FOR_OPERATOR_REVIEW',JSON.stringify({status:'CLOSED',comment:input.comment,meaning:'Internal workflow closure only; no regulatory declaration'}),u.email);return {status:'CLOSED'};
 });}
