function bootstrap(){const u=user_();if(u.must_change_password==='YES')return {authRequiredPasswordChange:true,user:{email:u.email,name:u.name,must_change_password:'YES'}};const tasks=rows_('04_EVIDENCE_TRACKER').filter(t=>canTask_(u,t)),orders=rows_('01_SO_MASTER').filter(c=>canOrder_(u,c)&&c.creation_state!=='CREATING'),supplier=u.role==='SUPPLIER_USER',ids=new Set(orders.map(c=>c.id)),materialIds=new Set(tasks.map(t=>t.material_id));
 const materials=rows_('02_SO_ITEM_MATERIAL').filter(m=>ids.has(m.case_id)&&(!supplier||materialIds.has(m.id)));
 const cases=orders.map(c=>{const own=tasks.filter(t=>t.case_id===c.id&&t.required!=='NO'),approved=own.filter(t=>t.status==='APPROVED').length,issues=supplier?[]:materials.filter(m=>m.case_id===c.id).flatMap(m=>materialIssues_(m));const expired=rows_('06_DOCUMENT_REGISTER').filter(d=>d.case_id===c.id&&d.active_version==='YES'&&d.expiry_date&&d.expiry_date<new Date().toISOString().slice(0,10));if(expired.length)issues.push('EXPIRED_CERTIFICATE');return {...c,folder:supplier||!hasCapability_(u,'SO_VIEW')?'':c.folder,so_document_id:hasCapability_(u,'SO_VIEW')?c.so_document_id:'',product_image_id:supplier?'':c.product_image_id,readiness:own.length?Math.round(approved*100/own.length):0,total:own.length,accepted:approved,issues,status:c.status==='CLOSED'?'CLOSED':own.some(t=>['REJECTED','MORE_INFO_REQUIRED'].includes(t.status))?'ACTION_REQUIRED':own.length&&approved===own.length&&!issues.length&&aiCoverageCurrent_(c.id)?'READY_FOR_OPERATOR_REVIEW':own.some(t=>['UPLOADED','SUBMITTED','IN_REVIEW'].includes(t.status))?'IN_REVIEW':'COLLECTING_EVIDENCE'};});
 const docs=rows_('06_DOCUMENT_REGISTER').filter(d=>ids.has(d.case_id)&&documentVisible_(d,u)&&(!supplier||tasks.some(t=>t.id===d.task_id)&&d.supplier_id===u.supplier_id)).map(d=>{const copy={...d};delete copy.file_id;delete copy.request_key;if(supplier){delete copy.review_comment;delete copy.uploaded_by;delete copy.reviewed_by;}return copy;});
 const chain=rows_('15_SUPPLY_CHAIN').filter(n=>ids.has(n.case_id)&&(!supplier||materialIds.has(n.material_id)&&n.supplier_id===u.supplier_id)),geo=rows_('17_GEO_LOCATIONS').filter(g=>ids.has(g.case_id)&&(!supplier||materialIds.has(g.material_id)&&g.supplier_id===u.supplier_id));
 const owners=u.role==='ADMIN'?rows_('05_OWNER_MASTER'):['MARKETING','EUDR_REVIEWER'].includes(u.role)?rows_('05_OWNER_MASTER').filter(x=>x.active==='YES').map(x=>({email:x.email,name:x.name,role:x.role,supplier_id:x.supplier_id})):[];
 return {user:{...u,capabilities:capabilities_(u)},products:supplier?[]:rows_('24_SO_PRODUCTS').filter(p=>ids.has(p.case_id)),requirements:hasCapability_(u,'POLICY_EDIT')?rows_('03_EVIDENCE_REQUIREMENT'):[],cases,tasks:tasks.map(t=>t.evidence==='Sales order'&&!hasCapability_(u,'SO_VIEW')?{...t,document_id:'',note:''}:t),materials:materials.map(m=>({...m,folder:supplier?'':m.folder})),docs,owners,chain,geo,suppliers:rows_('14_SUPPLIERS').filter(s=>!supplier||s.id===u.supplier_id),notifications:rows_('20_NOTIFICATIONS').filter(n=>n.email===u.email&&ids.has(n.case_id)),audit:supplier||!hasCapability_(u,'SO_VIEW')?[]:rows_('08_ACTIVITY_LOG').filter(a=>u.role==='ADMIN'||ids.has(a.case_id)).slice(-250),countryRisk:supplier?[]:rows_('22_COUNTRY_RISK').filter(r=>r.rule_version===config_('COUNTRY_RISK_VERSION')),settings:u.role==='ADMIN'?rows_('09_CONFIG'):[],legal:supplier?null:legalState_(),rulesConfirmed:config_('RULES_CONFIRMED')==='YES'};
}
function completeCase(caseId,input){const u=requireCapability_('WORKFLOW_CLOSE');order_(caseId,u);if(!input||input.confirmed!==true||!text_(input.comment||'',2000))fail_('HUMAN_CONFIRMATION_REQUIRED','Human closure confirmation and notes required');return lock_(()=>{
 const required=rows_('04_EVIDENCE_TRACKER').filter(t=>t.case_id===caseId&&t.required!=='NO'),materials=rows_('02_SO_ITEM_MATERIAL').filter(m=>m.case_id===caseId);
 if(rows_('07_AI_REVIEW_QUEUE').some(f=>f.case_id===caseId&&f.status!=='REVIEWED')||!rows_('18_AI_PROMPT_RUNS').some(r=>r.case_id===caseId&&r.function==='DOCUMENT_REVIEW'&&r.result_status==='REVIEWED'))fail_('AI_REVIEW_REQUIRED','Complete human review of AI findings');
 if(config_('RULES_CONFIRMED')!=='YES'||!required.length||required.some(t=>t.status!=='APPROVED')||!materials.length||materials.some(m=>materialIssues_(m).length))fail_('EVIDENCE_INCOMPLETE','Resolve required evidence and traceability before closure');
 if(!aiCoverageCurrent_(caseId))fail_('AI_REVIEW_REQUIRED','Review all current source versions before closure');
 if(legalState_().reviewDue)fail_('LEGAL_REVIEW_DUE','Legal baseline review is due');
 if(rows_('06_DOCUMENT_REGISTER').some(d=>d.case_id===caseId&&d.active_version==='YES'&&d.expiry_date&&d.expiry_date<new Date().toISOString().slice(0,10)))fail_('EVIDENCE_INCOMPLETE','Resolve expired certificates before closure');
 if(!rows_('19_EXPORT_LOG').some(ex=>ex.case_id===caseId&&ex.include_history!=='YES'))fail_('EXPORT_REQUIRED','Create an approved evidence export first');
 patch_('01_SO_MASTER',caseId,{status:'CLOSED',updated_at:now_()});audit_('ORDER_CLOSED',caseId,caseId,'READY_FOR_OPERATOR_REVIEW',JSON.stringify({status:'CLOSED',comment:input.comment,meaning:'Internal workflow closure only; no regulatory declaration'}),u.email);return {status:'CLOSED'};
 });}
function getMaterialReadiness(caseId){const u=user_();order_(caseId,u);if(u.role==='SUPPLIER_USER')fail_('PERMISSION_DENIED','Internal summary');const docs=rows_('06_DOCUMENT_REGISTER'),tasks=rows_('04_EVIDENCE_TRACKER'),geo=rows_('17_GEO_LOCATIONS'),nodes=rows_('15_SUPPLY_CHAIN'),findings=rows_('07_AI_REVIEW_QUEUE');return rows_('02_SO_ITEM_MATERIAL').filter(m=>m.case_id===caseId).map(m=>{const required=tasks.filter(t=>t.material_id===m.id&&t.required!=='NO'),plots=geo.filter(g=>g.material_id===m.id),issues=materialIssues_(m);return {material_id:m.id,material_defined:true,material_po_available:!!m.supplier_po,direct_supplier_recorded:nodes.some(n=>n.material_id===m.id&&!n.parent_id),supply_chain_complete:!chainIssues_(m.id).length,required_evidence_submitted:required.length>0&&required.every(t=>['SUBMITTED','IN_REVIEW','APPROVED'].includes(t.status)),required_evidence_approved:required.length>0&&required.every(t=>t.status==='APPROVED'),geo_available:plots.length>0,geo_human_reviewed:plots.length>0&&plots.every(g=>g.verification_status==='VERIFIED'),unresolved_mismatches:findings.filter(f=>f.material_id===m.id&&f.status!=='REVIEWED').length,status:issues.length?'BLOCKED':required.length&&required.every(t=>t.status==='APPROVED')&&aiCoverageCurrent_(caseId)?'READY_FOR_OPERATOR_REVIEW':'REVIEW_REQUIRED',issues};});}
// The complete checklist is requested only when a reviewer opens the final dossier step.
function getDossierReview(caseId){const u=requireCapability_('WORKFLOW_CLOSE'),c=order_(caseId,u),blockers=[],add=(code,details)=>blockers.push({code,details});
 const materials=rows_('02_SO_ITEM_MATERIAL').filter(m=>m.case_id===caseId),tasks=rows_('04_EVIDENCE_TRACKER').filter(t=>t.case_id===caseId&&t.required!=='NO');
 if(!materials.length)add('MISSING_MATERIAL','No material registered');
 for(const m of materials)for(const issue of [...new Set(materialIssues_(m))])add(issue,m.material||m.id);
 if(!tasks.length)add('MISSING_EVIDENCE','No required evidence tasks');
 for(const t of tasks)if(t.status!=='APPROVED')add('EVIDENCE_NOT_APPROVED',(t.evidence||t.id)+' · '+(t.status||'MISSING'));
 if(rows_('07_AI_REVIEW_QUEUE').some(f=>f.case_id===caseId&&f.status!=='REVIEWED')||!rows_('18_AI_PROMPT_RUNS').some(r=>r.case_id===caseId&&r.function==='DOCUMENT_REVIEW'&&r.result_status==='REVIEWED')||!aiCoverageCurrent_(caseId))add('AI_REVIEW_REQUIRED','Review findings against current source versions');
 if(config_('RULES_CONFIRMED')!=='YES'||legalState_().reviewDue)add('LEGAL_REVIEW_DUE','Legal baseline requires authorized review');
 if(rows_('06_DOCUMENT_REGISTER').some(d=>d.case_id===caseId&&d.active_version==='YES'&&d.expiry_date&&d.expiry_date<new Date().toISOString().slice(0,10)))add('EXPIRED_CERTIFICATE','Review expired active evidence');
 if(!rows_('19_EXPORT_LOG').some(ex=>ex.case_id===caseId&&ex.include_history!=='YES'))add('EXPORT_REQUIRED','Create the approved evidence export');
 return {order_id:c.id,ready:blockers.length===0,blockers,materials:getMaterialReadiness(caseId)};
}
function aiCoverageCurrent_(caseId){const active=rows_('06_DOCUMENT_REGISTER').filter(d=>d.case_id===caseId&&d.active_version==='YES'&&['SO','EVIDENCE'].includes(d.kind)),covered=new Set(rows_('18_AI_PROMPT_RUNS').filter(r=>r.case_id===caseId&&r.function==='DOCUMENT_REVIEW'&&r.result_status==='REVIEWED').flatMap(r=>jsonList_(r.source_document_ids)));return active.length>0&&active.every(d=>covered.has(d.id));}
function reopenCase(caseId,input){const u=requireCapability_('WORKFLOW_CLOSE');return withOperation_(()=>{const c=order_(caseId,u),comment=text_(input.comment||'',2000);if(input.confirmed!==true||!comment)fail_('HUMAN_CONFIRMATION_REQUIRED','Reason required');patch_('01_SO_MASTER',caseId,{status:'REVIEW_REQUIRED',updated_at:now_()});auditOnce_('ORDER_REOPENED',caseId,caseId,c.status,JSON.stringify({status:'REVIEW_REQUIRED',comment}),u);return {status:'REVIEW_REQUIRED'};});}
